// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QQ.Production.Intraday.Infrastructure.SqlServer;

#nullable disable

namespace QQ.Production.Intraday.Infrastructure.SqlServer.Migrations
{
    [DbContext(typeof(IntradayDbContext))]
    [Migration("20260430082145_EnforceReferenceDataUniqueness")]
    partial class EnforceReferenceDataUniqueness
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QQ.Production.Intraday.Domain.BarBuildRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BarsCreated")
                        .HasColumnType("int");

                    b.Property<int>("BarsUpdated")
                        .HasColumnType("int");

                    b.Property<string>("BuilderVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Timeframe")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BarBuildRuns");
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.BrokerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("FundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FundId", "AccountCode")
                        .IsUnique()
                        .HasFilter("[IsEnabled] = 1");

                    b.ToTable("BrokerAccounts");
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.ChildOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BaseQuantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<string>("ClientOrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("OrderType")
                        .HasColumnType("int");

                    b.Property<Guid>("ParentOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Side")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TimeInForce")
                        .HasColumnType("int");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("VenueQuantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.HasKey("Id");

                    b.HasIndex("ClientOrderId")
                        .IsUnique();

                    b.HasIndex("ParentOrderId");

                    b.HasIndex("VenueId");

                    b.ToTable("ChildOrders");
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.DriftSnapshot", b =>
                {
                    b.Property<Guid>("ModelRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CurrentBaseQuantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("CurrentVenueQuantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("DriftBaseQuantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("DriftVenueQuantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("TargetBaseQuantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("TargetVenueQuantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.HasKey("ModelRunId", "InstrumentId");

                    b.HasIndex("InstrumentId");

                    b.ToTable("DriftSnapshots");
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.ExecutionReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AveragePrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<string>("BrokerExecutionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrokerOrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ChildOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientOrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CumulativeQuantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<int>("ExecutionReportType")
                        .HasColumnType("int");

                    b.Property<decimal>("LastPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("LastQuantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("LeavesQuantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.HasIndex("ChildOrderId", "ReceivedAtUtc");

                    b.ToTable("ExecutionReports");
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.Fill", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BaseQuantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<string>("BrokerExecutionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("ChildOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Side")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TradeDateUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("VenueQuantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.HasKey("Id");

                    b.HasIndex("ChildOrderId");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("VenueId", "BrokerExecutionId")
                        .IsUnique();

                    b.ToTable("Fills");
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.Fund", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[IsEnabled] = 1");

                    b.ToTable("Funds");
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.Instrument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssetClass")
                        .HasColumnType("int");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("PricePrecision")
                        .HasColumnType("int");

                    b.Property<int>("QuantityPrecision")
                        .HasColumnType("int");

                    b.Property<string>("QuoteCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "AssetClass")
                        .IsUnique()
                        .HasFilter("[IsEnabled] = 1");

                    b.ToTable("Instruments");
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.InstrumentRiskLimit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxExposureUsd")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("MaxTradeNotionalUsd")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<Guid>("RiskLimitSetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("RiskLimitSetId", "InstrumentId")
                        .IsUnique()
                        .HasFilter("[IsEnabled] = 1");

                    b.ToTable("InstrumentRiskLimits");
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.KillSwitchState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("KillSwitchStates");
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.MarketDataBar", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AskClose")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("AskHigh")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("AskLow")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("AskOpen")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<DateTimeOffset>("BarEndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("BarStartUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("BidClose")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("BidHigh")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("BidLow")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("BidOpen")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<Guid?>("BuildRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuilderVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FirstSnapshotUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastSnapshotUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("MidClose")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("MidHigh")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("MidLow")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("MidOpen")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<int>("ObservationCount")
                        .HasColumnType("int");

                    b.Property<int>("QualityStatus")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SpreadAverage")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("SpreadClose")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("SpreadHigh")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("SpreadLow")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("SpreadOpen")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<int>("Timeframe")
                        .HasColumnType("int");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.HasIndex("InstrumentId", "VenueId", "Timeframe", "BarStartUtc")
                        .IsUnique();

                    b.ToTable("MarketDataBars");
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.MarketDataSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Ask")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("Bid")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("ExplicitMid")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSynthetic")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("SequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("SourceTimestampUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.HasIndex("InstrumentId", "VenueId", "ReceivedAtUtc");

                    b.ToTable("MarketDataSnapshots");
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.ModelRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AsOfUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("EffectiveAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FrequencyMinutes")
                        .HasColumnType("int");

                    b.Property<Guid>("FundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InputHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NavUsd")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TargetQuantityMode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("FundId", "IsProcessed", "ReceivedAtUtc");

                    b.ToTable("ModelRuns");
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.NavSnapshot", b =>
                {
                    b.Property<Guid>("FundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AsOfUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("NavUsd")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.HasKey("FundId", "AsOfUtc");

                    b.ToTable("NavSnapshots");
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.ParentOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Algo")
                        .HasColumnType("int");

                    b.Property<decimal>("BaseQuantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<string>("ClientOrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Side")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TradeIntentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClientOrderId")
                        .IsUnique();

                    b.HasIndex("TradeIntentId");

                    b.ToTable("ParentOrders");
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.PositionLedgerEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BaseQuantityDelta")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("FundId", "InstrumentId", "CreatedAtUtc");

                    b.ToTable("PositionLedgerEvents");
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.ReconciliationBreak", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("InstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReconciliationRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReconciliationRunId", "Severity", "Status");

                    b.ToTable("ReconciliationBreaks");
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.ReconciliationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("HasBlockingBreaks")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModelRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Phase")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModelRunId");

                    b.ToTable("ReconciliationRuns");
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.RiskDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RejectReason")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TradeIntentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TradeIntentId");

                    b.ToTable("RiskDecisions");
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.RiskLimit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("RiskLimitSetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Value")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.HasKey("Id");

                    b.HasIndex("RiskLimitSetId", "Name")
                        .IsUnique();

                    b.ToTable("RiskLimits");
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.RiskLimitSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("GlobalTradingEnabled")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxGrossExposureUsd")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<long>("MaxMarketDataAge")
                        .HasColumnType("bigint");

                    b.Property<long>("MaxModelRunAge")
                        .HasColumnType("bigint");

                    b.Property<decimal>("MinDriftVenueQuantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("PositionToleranceBaseQuantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.HasKey("Id");

                    b.HasIndex("FundId")
                        .IsUnique();

                    b.ToTable("RiskLimitSets");
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.TargetPosition", b =>
                {
                    b.Property<Guid>("ModelRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TargetBaseQuantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("TargetNotionalUsd")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<int>("TargetQuantityMode")
                        .HasColumnType("int");

                    b.Property<decimal>("TargetVenueQuantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.HasKey("ModelRunId", "InstrumentId");

                    b.HasIndex("InstrumentId");

                    b.ToTable("TargetPositions");
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.TargetWeight", b =>
                {
                    b.Property<Guid>("ModelRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RawSecurityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.HasKey("ModelRunId", "InstrumentId");

                    b.HasIndex("InstrumentId");

                    b.ToTable("TargetWeights");
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.TradeIntent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModelRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RequestedBaseQuantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("RequestedVenueQuantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<int>("Side")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FundId");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("ModelRunId", "InstrumentId");

                    b.ToTable("TradeIntents");
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.TradingWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("ClosesAtUtc")
                        .HasColumnType("time");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("FlattenAtUtc")
                        .HasColumnType("time");

                    b.Property<Guid>("FundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<TimeOnly>("NoNewOrdersAfterUtc")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("OpensAtUtc")
                        .HasColumnType("time");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TradingEnabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FundId", "ModelName", "DayOfWeek")
                        .IsUnique()
                        .HasFilter("[IsEnabled] = 1");

                    b.ToTable("TradingWindows");
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("VenueType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[IsEnabled] = 1");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.VenueInstrumentMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ContractSize")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<decimal>("MinOrderQuantity")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("PriceTickSize")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("QuantityStep")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VenueInstrumentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VenueSymbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("VenueId", "InstrumentId")
                        .IsUnique()
                        .HasFilter("[IsEnabled] = 1");

                    b.HasIndex("VenueId", "VenueSymbol")
                        .IsUnique()
                        .HasFilter("[IsEnabled] = 1");

                    b.ToTable("VenueInstrumentMappings");
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.VenueRiskLimit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxTradeNotionalUsd")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<Guid>("RiskLimitSetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.HasIndex("RiskLimitSetId", "VenueId")
                        .IsUnique()
                        .HasFilter("[IsEnabled] = 1");

                    b.ToTable("VenueRiskLimits");
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.BrokerAccount", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Domain.Fund", null)
                        .WithMany()
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.ChildOrder", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Domain.ParentOrder", null)
                        .WithMany()
                        .HasForeignKey("ParentOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QQ.Production.Intraday.Domain.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.DriftSnapshot", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Domain.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QQ.Production.Intraday.Domain.ModelRun", null)
                        .WithMany()
                        .HasForeignKey("ModelRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.ExecutionReport", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Domain.ChildOrder", null)
                        .WithMany()
                        .HasForeignKey("ChildOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QQ.Production.Intraday.Domain.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.Fill", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Domain.ChildOrder", null)
                        .WithMany()
                        .HasForeignKey("ChildOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QQ.Production.Intraday.Domain.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QQ.Production.Intraday.Domain.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.InstrumentRiskLimit", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Domain.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.MarketDataBar", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Domain.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QQ.Production.Intraday.Domain.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.MarketDataSnapshot", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Domain.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QQ.Production.Intraday.Domain.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.ModelRun", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Domain.Fund", null)
                        .WithMany()
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.NavSnapshot", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Domain.Fund", null)
                        .WithMany()
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.ParentOrder", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Domain.TradeIntent", null)
                        .WithMany()
                        .HasForeignKey("TradeIntentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.PositionLedgerEvent", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Domain.Fund", null)
                        .WithMany()
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QQ.Production.Intraday.Domain.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.ReconciliationBreak", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Domain.ReconciliationRun", null)
                        .WithMany()
                        .HasForeignKey("ReconciliationRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.ReconciliationRun", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Domain.ModelRun", null)
                        .WithMany()
                        .HasForeignKey("ModelRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.RiskDecision", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Domain.TradeIntent", null)
                        .WithMany()
                        .HasForeignKey("TradeIntentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.RiskLimitSet", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Domain.Fund", null)
                        .WithMany()
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.TargetPosition", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Domain.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QQ.Production.Intraday.Domain.ModelRun", null)
                        .WithMany()
                        .HasForeignKey("ModelRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.TargetWeight", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Domain.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QQ.Production.Intraday.Domain.ModelRun", null)
                        .WithMany()
                        .HasForeignKey("ModelRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.TradeIntent", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Domain.Fund", null)
                        .WithMany()
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QQ.Production.Intraday.Domain.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QQ.Production.Intraday.Domain.ModelRun", null)
                        .WithMany()
                        .HasForeignKey("ModelRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.TradingWindow", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Domain.Fund", null)
                        .WithMany()
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.VenueInstrumentMapping", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Domain.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QQ.Production.Intraday.Domain.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Domain.VenueRiskLimit", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Domain.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
