using QQ.Production.Intraday.Infrastructure.PostgreSql;

namespace QQ.Production.Intraday.Tools.OperationalReporting;

public static class Arch7bPostgreSqlTransportOperationalStatusDefinitions
{
    public static IReadOnlyList<OperationalStatusCodeDefinition> All { get; } =
    [
        Code(
            Arch7bPostgreSqlTransportProfileContract.ColdTimeoutMismatch,
            "The cold Npgsql timeout differs from the qualified 20-second direct profile."),
        Code("ARCH7B_POSTGRESQL_TRANSPORT_CONTRACT_MISMATCH",
            "The requested transport contract version is not authoritative."),
        Code("ARCH7B_POSTGRESQL_TRANSPORT_PROFILE_MISMATCH",
            "The requested transport profile is not the direct Primary RDS profile."),
        Code("ARCH7B_POSTGRESQL_EXECUTION_HOST_IDENTITY_MISMATCH",
            "The execution host identity differs from the qualified Primary EC2 host."),
        Code("ARCH7B_POSTGRESQL_LOOPBACK_FORBIDDEN",
            "A loopback PostgreSQL topology was requested."),
        Code("ARCH7B_POSTGRESQL_DIRECT_RDS_IDENTITY_MISMATCH",
            "The RDS instance, endpoint, VPC or security-group identity differs."),
        Code("ARCH7B_POSTGRESQL_DIRECT_ENDPOINT_MISMATCH",
            "The requested PostgreSQL endpoint differs from the direct RDS endpoint."),
        Code("ARCH7B_POSTGRESQL_DIRECT_PORT_MISMATCH",
            "The requested PostgreSQL port differs from 5432."),
        Code("ARCH7B_POSTGRESQL_RUNTIME_PROFILE_MISMATCH",
            "The PostgreSQL, Npgsql or .NET profile declaration differs."),
        Code("ARCH7B_POSTGRESQL_DOTNET_RUNTIME_VERSION_MISMATCH",
            "The loaded .NET runtime differs from the qualified runtime."),
        Code("ARCH7B_POSTGRESQL_NPGSQL_RUNTIME_VERSION_MISMATCH",
            "The loaded Npgsql assembly differs from the qualified runtime."),
        Code("ARCH7B_POSTGRESQL_VERIFY_FULL_REQUIRED",
            "TLS hostname and chain validation is not VerifyFull."),
        Code("ARCH7B_POSTGRESQL_POSTGRES_NEGOTIATION_REQUIRED",
            "PostgreSQL SSL negotiation is not selected."),
        Code("ARCH7B_POSTGRESQL_GSS_DISABLE_REQUIRED",
            "GSS encryption is not explicitly disabled."),
        Code("ARCH7B_POSTGRESQL_CERTIFICATE_VALIDATION_MISMATCH",
            "The certificate validation policy is not chain and hostname."),
        Code("ARCH7B_POSTGRESQL_ROOT_CA_FILE_MISSING",
            "The exact RDS root certificate file is missing."),
        Code("ARCH7B_POSTGRESQL_ROOT_CA_SHA256_MISMATCH",
            "The RDS root certificate SHA-256 differs from the qualified root."),
        Code("ARCH7B_POSTGRESQL_POOLING_REQUIRED",
            "The one-shot warm connection pool is disabled."),
        Code("ARCH7B_POSTGRESQL_MINIMUM_POOL_SIZE_MISMATCH",
            "The minimum pool size differs from one."),
        Code("ARCH7B_POSTGRESQL_MAXIMUM_POOL_SIZE_MISMATCH",
            "The maximum pool size differs from one."),
        Code("ARCH7B_POSTGRESQL_MULTIPLEXING_FORBIDDEN",
            "Npgsql multiplexing is enabled."),
        Code("ARCH7B_POSTGRESQL_NO_RESET_ON_CLOSE_FORBIDDEN",
            "NoResetOnClose would weaken logical checkout isolation."),
        Code("ARCH7B_POSTGRESQL_ENLIST_FORBIDDEN",
            "Ambient transaction enlistment is enabled."),
        Code("ARCH7B_POSTGRESQL_BOUNDED_LIFETIME_PROFILE_MISMATCH",
            "Command, idle or physical lifetime bounds differ."),
        Code("ARCH7B_POSTGRESQL_SECRET_OBSERVABILITY_FORBIDDEN",
            "A secret-bearing Npgsql observability option is enabled."),
        Code("ARCH7B_POSTGRESQL_CONNECT_HOST_OVERRIDE_FORBIDDEN",
            "A physical connect-host override was requested."),
        Code("ARCH7B_POSTGRESQL_CONNECT_PORT_OVERRIDE_FORBIDDEN",
            "A physical connect-port override was requested."),
        Code("ARCH7B_POSTGRESQL_TARGET_HOST_OVERRIDE_FORBIDDEN",
            "A TLS TargetHost override was requested."),
        Code("ARCH7B_POSTGRESQL_FALLBACK_TRANSPORT_FORBIDDEN",
            "A relay, SSM or portproxy fallback was requested."),
        Code("ARCH7B_POSTGRESQL_MULTIPLE_DATA_SOURCES_FORBIDDEN",
            "More than one NpgsqlDataSource was created in the process."),
        Code("ARCH7B_POSTGRESQL_COLD_OPEN_MUST_RUN_ONCE",
            "The cold physical open was started more than once."),
        Code("ARCH7B_POSTGRESQL_COLD_OPEN_ALREADY_OBSERVED",
            "More than one cold physical connection was observed."),
        Code(
            "ARCH7B_POSTGRESQL_FIRST_AUTHENTICATED_CONNECTION_SLO_EXCEEDED",
            "The first authenticated connection exceeded 20 seconds."),
        Code("ARCH7B_POSTGRESQL_BACKEND_PROCESS_ID_INVALID",
            "PostgreSQL did not expose a valid backend process ID."),
        Code("ARCH7B_POSTGRESQL_COLD_CHECKOUT_STATE_INVALID",
            "The cold logical checkout state is inconsistent."),
        Code("ARCH7B_POSTGRESQL_WARM_CONNECTION_REQUIRED_BEFORE_P2",
            "Critical database work began before warm-up completed."),
        Code("ARCH7B_POSTGRESQL_LOGICAL_CHECKOUT_BEFORE_WARMUP",
            "A logical checkout began before the warm connection authority."),
        Code(
            Arch7bPostgreSqlWarmConnectionAuthority.ConcurrentCheckout,
            "More than one logical PostgreSQL connection was active."),
        Code(
            Arch7bPostgreSqlWarmConnectionAuthority.SlowPooledCheckout,
            "A warmed logical checkout exceeded 1000 milliseconds."),
        Code(
            Arch7bPostgreSqlWarmConnectionAuthority.PhysicalReconnect,
            "The backend process ID changed after broker P2."),
        Code("ARCH7B_POSTGRESQL_WARM_BACKEND_PROCESS_ID_MISMATCH",
            "A logical checkout did not reuse the warmed backend process."),
        Code("ARCH7B_POSTGRESQL_LOGICAL_CHECKOUT_STATE_INVALID",
            "A logical checkout close did not match an active checkout."),
        Code("ARCH7B_POSTGRESQL_WARM_CONNECTION_EVIDENCE_UNAVAILABLE",
            "Warm-connection evidence was requested before warm-up."),
        Code("ARCH7B_POSTGRESQL_TLS_NOT_ACTIVE",
            "The warmed PostgreSQL backend is not using TLS."),
        Code("ARCH7B_POSTGRESQL_WARM_IDENTITY_ROW_MISSING",
            "The warm identity readback returned no row."),
        Code("ARCH7B_POSTGRESQL_WARM_DATABASE_MISMATCH",
            "The warmed connection reached a different database."),
        Code("ARCH7B_POSTGRESQL_WARM_USER_MISMATCH",
            "The warmed connection authenticated a different role."),
        Code("ARCH7B_POSTGRESQL_WARM_VERSION_MISMATCH",
            "The warmed connection reached a different PostgreSQL major."),
        Code("ARCH7B_POSTGRESQL_WARM_TIMEZONE_NOT_UTC",
            "The warmed PostgreSQL session timezone is not UTC."),
        Code("ARCH7B_POSTGRESQL_WARM_DATABASE_TIME_NOT_UTC",
            "The warmed PostgreSQL clock value is not UTC."),
        Code("ARCH7B_POSTGRESQL_WARM_TARGET_FINGERPRINT_INVALID",
            "The warmed target fingerprint is not a full SHA-256."),
        Code("ARCH7B_POSTGRESQL_USERNAME_REQUIRED",
            "The PostgreSQL role name is missing."),
        Code("ARCH7B_POSTGRESQL_PASSWORD_REQUIRED",
            "The bounded secret mechanism did not provide a password."),
        Code("ARCH7B_POSTGRESQL_APPLICATION_NAME_REQUIRED",
            "The bounded PostgreSQL application name is missing.")
    ];

    private static OperationalStatusCodeDefinition Code(
        string exactCode,
        string description) =>
        new(
            exactCode,
            "ARCH7B_POSTGRESQL_TRANSPORT",
            "SECURITY",
            OperationalBreakSeverity.Critical,
            "PMS_SHADOW",
            description,
            $"Stop the fast path and inspect {exactCode}; do not select a fallback transport.",
            AutomaticResolutionPossible: false,
            BlocksTrading: true,
            BlocksAccounting: true,
            EvidenceRequirements:
                "Exact transport profile SHA, target fingerprint, warm backend PID and checkout timeline.",
            Supersedes: null,
            IntroducedByContractVersion:
                Arch7bPostgreSqlTransportProfile.Version);
}
