using QQ.Production.Intraday.Infrastructure.PostgreSql;

namespace QQ.Production.Intraday.Tools.OperationalReporting;

public static class Arch7bPositionMarketOperationalStatusDefinitions
{
    public static IReadOnlyList<OperationalStatusCodeDefinition> All { get; } =
    [
        Code("POSITION_MARKET_SLOT_LINEAGE_MISSING", OperationalBreakSeverity.Error,
            "The selected operational revision has no position-to-market lineage evidence.",
            "Stop progression and locate the exact finalized lineage path and SHA."),
        Code("POSITION_MARKET_SLOT_LINEAGE_CONTRADICTORY", OperationalBreakSeverity.Critical,
            "Position-to-market lineage evidence contradicts its content-addressed binding.",
            "Stop progression and compare the selected snapshot, slot, mapping and manifest identities."),
        Code("POSITION_MARKET_REVISION_BINDING_MISSING", OperationalBreakSeverity.Error,
            "The economic revision has no position-to-market revision input binding.",
            "Stop progression and locate the exact revision binding path and SHA."),
        Code("POSITION_MARKET_ARCH7A_BINDING_MISMATCH", OperationalBreakSeverity.Critical,
            "ARCH7A does not bind the exact economic revision named by position-to-market lineage.",
            "Stop progression and requalify ARCH7A against the exact bound revision."),
        Code(Arch7bPositionMarketSlotLineageContract.BindingRequired,
            OperationalBreakSeverity.Error, "Position-to-market slot binding is required.",
            "Provide the exact content-addressed binding before progression."),
        Code(Arch7bPositionMarketSlotLineageContract.PositionSnapshotMismatch,
            OperationalBreakSeverity.Critical, "The position snapshot binding is inconsistent.",
            "Stop and reselect the exact 99-line runtime snapshot."),
        Code(Arch7bPositionMarketSlotLineageContract.SourceIngestionMismatch,
            OperationalBreakSeverity.Critical, "The source ingestion binding is inconsistent.",
            "Stop and use the ingestion selected by the position snapshot."),
        Code(Arch7bPositionMarketSlotLineageContract.RequiredUniverseMismatch,
            OperationalBreakSeverity.Critical, "The required PMS universe binding is inconsistent.",
            "Stop and use the exact required 99-instrument universe."),
        Code(Arch7bPositionMarketSlotLineageContract.SlotMismatch,
            OperationalBreakSeverity.Critical, "The selected slot binding is inconsistent.",
            "Stop and use the slot named by the draft."),
        Code(Arch7bPositionMarketSlotLineageContract.MappingAuthorityMismatch,
            OperationalBreakSeverity.Critical, "The market mapping authority is inconsistent.",
            "Stop and use the exact 49-symbol and mapping sets."),
        Code(Arch7bPositionMarketSlotLineageContract.ManifestBindingMismatch,
            OperationalBreakSeverity.Critical, "The market manifest binding is inconsistent.",
            "Stop and verify all manifest, clock and selection hashes."),
        Code(Arch7bPositionMarketSlotLineageContract.RevisionInputMismatch,
            OperationalBreakSeverity.Critical, "The economic revision input binding is inconsistent.",
            "Stop and bind the exact lineage to the exact revision."),
        Code(Arch7bPositionMarketRuntimeContract.DraftPublicationFailed,
            OperationalBreakSeverity.Error, "The draft could not be published atomically.",
            "Stop before Market Data and inspect the draft output root."),
        Code(Arch7bPositionMarketRuntimeContract.DraftEvidenceShaMismatch,
            OperationalBreakSeverity.Critical, "The draft file SHA does not match.",
            "Stop before Market Data and verify the content-addressed draft."),
        Code(Arch7bPositionMarketRuntimeContract.DraftAlreadyExists,
            OperationalBreakSeverity.Critical, "A one-shot draft path already exists.",
            "Use a new run root; never overwrite an earlier draft."),
        Code(Arch7bPositionMarketRuntimeContract.DraftNotBoundToSelectedSnapshot,
            OperationalBreakSeverity.Critical, "The draft does not bind the selected snapshot.",
            "Stop and rebuild the one-shot run from runtime selection."),
        Code(Arch7bPositionMarketRuntimeContract.DraftRequiredBeforeMarketCapture,
            OperationalBreakSeverity.Critical, "Market capture was requested without a draft.",
            "Stop before logon and provide the exact draft path and SHA."),
        Code(Arch7bPositionMarketRuntimeContract.LineageFinalizationFailed,
            OperationalBreakSeverity.Critical, "Position-to-market lineage finalization failed.",
            "Stop publication and inspect slot finalization evidence."),
        Code(Arch7bPositionMarketRuntimeContract.LineageNotInMarketManifest,
            OperationalBreakSeverity.Critical, "The market manifest does not bind lineage.",
            "Stop import and publish a manifest with the exact lineage path and SHA."),
        Code(Arch7bPositionMarketRuntimeContract.LineageNotInReadyMarker,
            OperationalBreakSeverity.Critical, "The ready marker does not bind lineage.",
            "Stop import and publish a marker with the exact lineage path and SHA."),
        Code(Arch7bPositionMarketRuntimeContract.CoverageIncomplete,
            OperationalBreakSeverity.Error, "Market coverage is below 49 symbols.",
            "Stop finalization and inspect the bounded market coverage evidence."),
        Code(Arch7bPositionMarketRuntimeContract.ProjectionCardinalityMismatch,
            OperationalBreakSeverity.Critical, "Projection cardinality is not 99/288/288.",
            "Stop persistence and inspect the production projection."),
        Code(Arch7bPositionMarketRuntimeContract.RevisionBindingRequired,
            OperationalBreakSeverity.Critical, "Revision input binding is required.",
            "Stop ARCH7A and provide the exact binding path and SHA."),
        Code(Arch7bPositionMarketRuntimeContract.RevisionBindingShaMismatch,
            OperationalBreakSeverity.Critical, "Revision input binding SHA does not match.",
            "Stop ARCH7A and verify the content-addressed binding."),
        Code(Arch7bPositionMarketRuntimeContract.Arch7aBindingRequired,
            OperationalBreakSeverity.Critical, "ARCH7A requires the exact bound revision.",
            "Stop qualification and use the revision named by the binding."),
        Code(Arch7bPositionMarketRuntimeContract.ReplayLineageMismatch,
            OperationalBreakSeverity.Critical, "Replay lineage differs from persisted authority.",
            "Reject replay and preserve the original revision."),
        Code(Arch7bPositionMarketRuntimeContract.ReplayMarketManifestMismatch,
            OperationalBreakSeverity.Critical, "Replay market manifest differs from persisted authority.",
            "Reject replay and preserve the original revision.")
    ];

    private static OperationalStatusCodeDefinition Code(
        string exactCode,
        OperationalBreakSeverity severity,
        string description,
        string operatorMeaning) =>
        new(exactCode, "QQ.Production.Intraday", "POSITION_MARKET_LINEAGE", severity,
            "PMS_SHADOW", description, operatorMeaning, true,
            true, true,
            "Content-addressed lineage, revision binding and ARCH7A revision identities.",
            null, Arch7bPositionMarketSlotLineageContract.Version);
}
