using QQ.Production.Intraday.Infrastructure.PostgreSql;

namespace QQ.Production.Intraday.Tools.OperationalReporting;

public static class Arch7bPositionImportOperationalStatusDefinitions
{
    public static IReadOnlyList<OperationalStatusCodeDefinition> All { get; } =
    [
        Code("ARCH7B_POSITION_BRACKET_STALE", "FRESHNESS",
            OperationalBreakSeverity.Error,
            "The bracketed broker position snapshot exceeds the canonical 300-second import deadline."),
        Code("ARCH7B_POSITION_IMPORT_PACKAGE_MISSING", "EVIDENCE",
            OperationalBreakSeverity.Error,
            "The content-addressed consumer package root is missing."),
        Code("ARCH7B_POSITION_IMPORT_PACKAGE_INCOMPLETE", "EVIDENCE",
            OperationalBreakSeverity.Error,
            "One or more required consumer package files are missing."),
        Code("ARCH7B_POSITION_IMPORT_CONSUMER_CONTRACT_MISMATCH", "LINEAGE",
            OperationalBreakSeverity.Error,
            "The package does not declare the qualified global-flat consumer contract."),
        Code("ARCH7B_POSITION_IMPORT_MANIFEST_FILE_MISSING", "EVIDENCE",
            OperationalBreakSeverity.Error,
            "A file declared by the consumer manifest is absent."),
        Code("ARCH7B_POSITION_IMPORT_MANIFEST_FILE_SHA_MISMATCH", "LINEAGE",
            OperationalBreakSeverity.Critical,
            "A declared package file differs from its manifest SHA-256."),
        Code("ARCH7B_POSITION_IMPORT_SNAPSHOT_CONTRACT_MISMATCH", "LINEAGE",
            OperationalBreakSeverity.Error,
            "The position snapshot contract differs from the qualified consumer contract."),
        Code("ARCH7B_POSITION_IMPORT_LINEAGE_MISMATCH", "LINEAGE",
            OperationalBreakSeverity.Critical,
            "Snapshot lines do not bind exactly to the source ingestion, session, universe, or bracket."),
        Code("ARCH7B_POSITION_IMPORT_LINE_SET_SHA_MISMATCH", "LINEAGE",
            OperationalBreakSeverity.Critical,
            "The normalized 99-line set differs from its content address."),
        Code("ARCH7B_POSITION_IMPORT_MANIFEST_BINDING_MISMATCH", "LINEAGE",
            OperationalBreakSeverity.Critical,
            "Manifest snapshot, universe, or line-set identity differs from the payload."),
        Code("ARCH7B_POSITION_IMPORT_SOURCE_INGESTION_MISSING", "PMS_IMPORT",
            OperationalBreakSeverity.Error,
            "The referenced completed PMS ingestion is absent."),
        Code("ARCH7B_POSITION_IMPORT_SOURCE_ACCOUNT_MISSING", "PMS_IMPORT",
            OperationalBreakSeverity.Error,
            "The referenced authoritative PMS account snapshot is absent."),
        Code("ARCH7B_POSITION_IMPORT_ROW_DELTA_MISMATCH", "PMS_IMPORT",
            OperationalBreakSeverity.Critical,
            "The atomic append produced a row count other than one snapshot plus 99 lines."),
        Code("ARCH7B_POSITION_IMPORT_TARGET_REJECTED", "SECURITY",
            OperationalBreakSeverity.Critical,
            "The requested target is outside the exact ARCH7B RDS TEST contract."),
        Code("ARCH7B_POSITION_IMPORT_DATABASE_IDENTITY_MISMATCH", "SECURITY",
            OperationalBreakSeverity.Critical,
            "The connected database identity differs from qq_pms_shadow_arch7b_test."),
        Code("ARCH7B_POSITION_IMPORT_POSTGRESQL_MAJOR_MISMATCH", "SECURITY",
            OperationalBreakSeverity.Critical,
            "The connected PostgreSQL major version differs from 18."),
        Code("ARCH7B_POSITION_IMPORT_DATABASE_VALUE_MISSING", "RDS",
            OperationalBreakSeverity.Error,
            "A mandatory database identity or transaction fact was not returned."),
        Code("ARCH7B_POSITION_IMPORT_CSV_JSON_MISMATCH", "LINEAGE",
            OperationalBreakSeverity.Critical,
            "The typed normalized CSV differs from snapshot.Lines."),
        Code("ARCH7B_POSITION_IMPORT_PACKAGE_INVENTORY_MISMATCH", "EVIDENCE",
            OperationalBreakSeverity.Critical,
            "The package contains a missing or undeclared entry."),
        Code("ARCH7B_POSITION_IMPORT_REPARSE_POINT_REJECTED", "SECURITY",
            OperationalBreakSeverity.Critical,
            "The package root or an entry resolves through a reparse point."),
        Code("ARCH7B_POSITION_IMPORT_LATEST_INGESTION_CHANGED", "LINEAGE",
            OperationalBreakSeverity.Critical,
            "The package no longer references the latest ingestion."),
        Code("ARCH7B_POSITION_IMPORT_MODEL_LINEAGE_CHANGED", "LINEAGE",
            OperationalBreakSeverity.Critical,
            "Model, weight, or strategy lineage differs from the package."),
        Code("ARCH7B_POSITION_IMPORT_QUBES_LINEAGE_CHANGED", "LINEAGE",
            OperationalBreakSeverity.Critical,
            "Qubes input lineage differs from the package."),
        Code("ARCH7B_POSITION_IMPORT_MAPPING_LINEAGE_CHANGED", "LINEAGE",
            OperationalBreakSeverity.Critical,
            "Security mapping lineage differs from the package."),
        Code("ARCH7B_POSITION_IMPORT_AUTHORIZATION_MISMATCH", "SECURITY",
            OperationalBreakSeverity.Critical,
            "The CLI, armed state and ready marker authorization differ."),
        Code("ARCH7B_POSITION_IMPORT_OWNER_MISMATCH", "SECURITY",
            OperationalBreakSeverity.Critical,
            "The CLI, owner lease, armed state and ready marker owner differ."),
        Code("ARCH7B_POSITION_IMPORT_REPOSITORY_STATE_MISMATCH", "LINEAGE",
            OperationalBreakSeverity.Critical,
            "The real clean Git HEAD differs from the build or marker."),
        Code("ARCH7B_POSITION_IMPORT_CHRONOLOGY_INVALID", "FRESHNESS",
            OperationalBreakSeverity.Critical,
            "The arm, broker bracket, ready and apply chronology is invalid."),
        Code("ARCH7B_POSITION_IMPORT_POST_COMMIT_READBACK_MISMATCH", "PMS_IMPORT",
            OperationalBreakSeverity.Critical,
            "Post-commit readback differs from the authorized append-only delta."),
        Code("ARCH7B_POSITION_IMPORT_INTRA_TRANSACTION_READBACK_MISMATCH", "PMS_IMPORT",
            OperationalBreakSeverity.Critical,
            "In-transaction readback differs from the authorized append-only delta."),
        Code("ARCH7B_POSITION_IMPORT_MANIFEST_FILE_IDENTITY_MISMATCH", "EVIDENCE",
            OperationalBreakSeverity.Critical,
            "A package entry differs from its SHA-256 or declared byte size."),
        Code("ARCH7B_POSITION_IMPORT_ARMED_STATE_MISMATCH", "SECURITY",
            OperationalBreakSeverity.Critical,
            "The armed-state evidence differs from the target or repository authority."),
        Code("ARCH7B_POSITION_IMPORT_UNIVERSE_SHA_MISMATCH", "LINEAGE",
            OperationalBreakSeverity.Critical,
            "The database-rebuilt required universe SHA differs from the package."),
        Code("ARCH7B_POSITION_IMPORT_REQUIRED_PRIVILEGE_MISSING", "SECURITY",
            OperationalBreakSeverity.Critical,
            "The bounded importer principal lacks a required SELECT or INSERT privilege."),
        Code("ARCH7B_POSITION_SNAPSHOT_MISSING_FOR_SLOT", "PMS_IMPORT",
            OperationalBreakSeverity.Critical,
            "No position snapshot exists for the requested source ingestion and slot."),
        Code("ARCH7B_POSITION_SNAPSHOT_STALE_FOR_SLOT", "FRESHNESS",
            OperationalBreakSeverity.Critical,
            "The latest pre-slot position snapshot is older than 300 seconds."),
        Code("NO_GO_ARCH7B_POSITION_IMPORT_DATABASE_CLOCK_AUTHORITY_CONVERSION_INVALID",
            "FRESHNESS", OperationalBreakSeverity.Critical,
            "The failed live run observed a host-timezone-dependent PostgreSQL clock conversion.",
            Arch7bPostgreSqlClockAuthorityContract.Version),
        Code("ARCH7B_POSITION_IMPORT_DATABASE_CLOCK_CLR_MAPPING_INVALID",
            "RDS", OperationalBreakSeverity.Critical,
            "The PostgreSQL timestamp driver mapping is not explicitly UTC.",
            Arch7bPostgreSqlClockAuthorityContract.Version),
        Code("ARCH7B_POSITION_IMPORT_DATABASE_CLOCK_EPOCH_MISMATCH",
            "RDS", OperationalBreakSeverity.Critical,
            "The typed PostgreSQL timestamp differs from its same-instant Unix epoch.",
            Arch7bPostgreSqlClockAuthorityContract.Version),
        Code("ARCH7B_POSITION_IMPORT_DATABASE_CLOCK_TYPE_INVALID",
            "RDS", OperationalBreakSeverity.Critical,
            "The PostgreSQL database clock is not timestamp with time zone.",
            Arch7bPostgreSqlClockAuthorityContract.Version),
        Code("ARCH7B_POSITION_IMPORT_DATABASE_TIMEZONE_NOT_UTC",
            "RDS", OperationalBreakSeverity.Critical,
            "The PostgreSQL clock-authority session timezone is not UTC.",
            Arch7bPostgreSqlClockAuthorityContract.Version)
    ];

    private static OperationalStatusCodeDefinition Code(
        string exactCode,
        string category,
        OperationalBreakSeverity severity,
        string description,
        string? introducedByContractVersion = null) =>
        new(
            exactCode,
            "ARCH7B_POSITION_IMPORT",
            category,
            severity,
            "PMS_SHADOW",
            description,
            $"Stop the import and inspect {exactCode} at the exact source package and target.",
            AutomaticResolutionPossible: severity is not OperationalBreakSeverity.Critical,
            BlocksTrading: true,
            BlocksAccounting: category is "PMS_IMPORT",
            EvidenceRequirements:
                "Exact package SHA identities, source lineage, target fingerprint and read-only plan.",
            Supersedes: null,
            IntroducedByContractVersion: introducedByContractVersion ??
                Arch7bPositionImportContract.Version);
}
