namespace QQ.Production.Intraday.Tools.OperationalReporting;

public static class OperationalStatusCodeInventory
{
    public static IReadOnlyList<OperationalStatusCodeDefinition> Additional { get; } =
    [
        Code("INGESTION_FAILED", "PMS_IMPORT", "IMPORT", OperationalBreakSeverity.Error),
        Code("INGESTION_FAILED_CLOSED", "PMS_IMPORT", "IMPORT", OperationalBreakSeverity.Error),
        Code("POLYGON_CALL_LEDGER_MISMATCH", "INTRADAY_MANIFEST", "MARKET_DATA",
            OperationalBreakSeverity.Error),
        Code("SLOT_HANDOFF_NOT_FINALIZED", "INTRADAY_MANIFEST", "HANDOFF",
            OperationalBreakSeverity.Error),
        Code("SLOT_FINALIZATION_DEADLINE_EXCEEDED", "INTRADAY_MANIFEST", "HANDOFF",
            OperationalBreakSeverity.Error),
        Code("QUBES_INPUT_INCOMPLETE", "INTRADAY_MANIFEST", "MODEL_LINEAGE",
            OperationalBreakSeverity.Error),
        Code("WEIGHTS_LINEAGE_INCOMPLETE", "INTRADAY_MANIFEST", "MODEL_LINEAGE",
            OperationalBreakSeverity.Error),
        Code("POSTGRESQL_ROW_COUNTS_MISSING", "INTRADAY_MANIFEST", "RDS",
            OperationalBreakSeverity.Error),
        Code("DAILY_SESSION_MISSING", "PMS_READ_MODEL", "IMPORT", OperationalBreakSeverity.Error),
        Code("SHADOW_DATA_STALE", "PMS_READ_MODEL", "IMPORT", OperationalBreakSeverity.Warning),
        Code("ROW_COUNT_MISMATCH", "PMS_READ_MODEL", "RDS", OperationalBreakSeverity.Error),
        Code("SOURCE_SESSION_NOT_COMPLETED", "ARCH7A_PREFLIGHT", "ARCH7A",
            OperationalBreakSeverity.Error),
        Code("SOURCE_SESSION_STALE", "ARCH7A_PREFLIGHT", "ARCH7A",
            OperationalBreakSeverity.Error),
        Code("SOURCE_LINEAGE_INCOMPLETE", "ARCH7A_PREFLIGHT", "MODEL_LINEAGE",
            OperationalBreakSeverity.Error),
        Code("SOURCE_ECONOMIC_REVISION_NOT_QUALIFYING", "ARCH7A_PREFLIGHT",
            "ECONOMIC_PROJECTION", OperationalBreakSeverity.Error),
        Code("NON_TEST_ENVIRONMENT_REJECTED", "ARCH7A_PREFLIGHT", "SECURITY",
            OperationalBreakSeverity.Critical),
        Code("REAL_ACCOUNT_REJECTED", "ARCH7A_PREFLIGHT", "SECURITY",
            OperationalBreakSeverity.Critical),
        Code("WORKING_LEAVES_POLICY_FORBIDS_CONSTRUCTION", "ARCH7A_PREFLIGHT",
            "AUTHORITY", OperationalBreakSeverity.Critical),
        Code("CRITICAL_RECONCILIATION_CONFLICT", "ARCH7A_PREFLIGHT",
            "RECONCILIATION", OperationalBreakSeverity.Critical),
        Code("ARCH7B_DUPLICATE_EXEC_ID_CONFLICT", "ARCH7B_LIFECYCLE",
            "EXECUTION_REPORT", OperationalBreakSeverity.Critical, pattern: true),
        Code("ARCH7B_CONFLICTING_FIX_SEQUENCE", "ARCH7B_LIFECYCLE",
            "FIX_SESSION", OperationalBreakSeverity.Critical, pattern: true),
        Code("ARCH7B_FIX_SEQUENCE_GAP", "ARCH7B_LIFECYCLE",
            "FIX_SESSION", OperationalBreakSeverity.Critical, pattern: true),
        Code("ARCH7B_EXECUTION_REPORT_INSTRUMENT_MISMATCH", "ARCH7B_LIFECYCLE",
            "EXECUTION_REPORT", OperationalBreakSeverity.Critical),
        Code("ARCH7B_FIX_SEQUENCE_INVALID", "ARCH7B_LIFECYCLE",
            "FIX_SESSION", OperationalBreakSeverity.Critical),
        Code("ARCH7B_RAW_MESSAGE_SHA256_INVALID", "ARCH7B_LIFECYCLE",
            "EXECUTION_REPORT", OperationalBreakSeverity.Critical),
        Code("ARCH7B_EXECUTION_REPORT_IDENTITY_INCOMPLETE", "ARCH7B_LIFECYCLE",
            "EXECUTION_REPORT", OperationalBreakSeverity.Critical),
        Code("ARCH7B_EXECUTION_REPORT_NUMERIC_INVALID", "ARCH7B_LIFECYCLE",
            "EXECUTION_REPORT", OperationalBreakSeverity.Critical),
        Code("ARCH7B_EXECUTION_REPORT_QUANTITY_INCONSISTENT", "ARCH7B_LIFECYCLE",
            "EXECUTION_REPORT", OperationalBreakSeverity.Critical),
        Code("ARCH7B_OPENING_ORDER_NOT_FILLED", "ARCH7B_LIFECYCLE",
            "ORDER", OperationalBreakSeverity.Critical),
        Code("ARCH7B_OPENING_FILL_CUMQTY_DIVERGENCE_EMERGENCY_STOP", "ARCH7B_LIFECYCLE",
            "FILL", OperationalBreakSeverity.Critical),
        Code("ARCH7B_FLATTEN_FILL_CUMQTY_DIVERGENCE_EMERGENCY_STOP", "ARCH7B_LIFECYCLE",
            "FILL", OperationalBreakSeverity.Critical),
        Code("MISSING_INTERNAL_FILL", "BROKER_RECONCILIATION", "FILL",
            OperationalBreakSeverity.Critical),
        Code("MISSING_BROKER_FILL", "BROKER_RECONCILIATION", "FILL",
            OperationalBreakSeverity.Critical),
        Code("DUPLICATE_EXECUTION", "BROKER_RECONCILIATION", "EXECUTION_REPORT",
            OperationalBreakSeverity.Critical),
        Code("POSITION_QUANTITY_MISMATCH", "BROKER_RECONCILIATION", "RECONCILIATION",
            OperationalBreakSeverity.Critical),
        Code("POSITION_INSTRUMENT_MISMATCH", "BROKER_RECONCILIATION", "RECONCILIATION",
            OperationalBreakSeverity.Critical),
        Code("OPEN_ORDER_MISSING_INTERNAL", "BROKER_RECONCILIATION", "ORDER",
            OperationalBreakSeverity.Critical),
        Code("OPEN_ORDER_MISSING_BROKER", "BROKER_RECONCILIATION", "ORDER",
            OperationalBreakSeverity.Critical),
        Code("LEAVES_MISMATCH", "BROKER_RECONCILIATION", "RECONCILIATION",
            OperationalBreakSeverity.Critical),
        Code("TERMINAL_STATE_MISMATCH", "BROKER_RECONCILIATION", "RECONCILIATION",
            OperationalBreakSeverity.Critical),
        Code("STALE_BROKER_SNAPSHOT", "BROKER_RECONCILIATION", "AUTHORITY",
            OperationalBreakSeverity.Warning),
        Code("SEQUENCE_GAP", "BROKER_RECONCILIATION", "FIX_SESSION",
            OperationalBreakSeverity.Critical),
        Code("UNRESOLVED_CANCEL_PENDING", "BROKER_RECONCILIATION", "ORDER",
            OperationalBreakSeverity.Critical),
        Code("UNKNOWN_ACCOUNT_SCOPE", "BROKER_RECONCILIATION", "SECURITY",
            OperationalBreakSeverity.Critical),
        Code("UNACCEPTABLE_BROKER_AUTHORITY_SOURCE", "BROKER_RECONCILIATION",
            "AUTHORITY", OperationalBreakSeverity.Critical),
        Code("NO_GO_BROKER_AUTHORITY_SOURCE_NOT_READY", "BROKER_RECONCILIATION",
            "AUTHORITY", OperationalBreakSeverity.Critical),
        Code("NO_GO_CRITICAL_BROKER_BREAK", "BROKER_RECONCILIATION",
            "RECONCILIATION", OperationalBreakSeverity.Critical),
        Code("NO_GO_BLOCKING_BROKER_BREAK", "BROKER_RECONCILIATION",
            "RECONCILIATION", OperationalBreakSeverity.Error)
    ];

    private static OperationalStatusCodeDefinition Code(
        string exactCode,
        string source,
        string category,
        OperationalBreakSeverity severity,
        bool pattern = false)
        => new(
            exactCode,
            source,
            category,
            severity,
            "PMS_SHADOW",
            pattern
                ? "Versioned dynamic blocker family; suffix values remain part of source evidence."
                : "Versioned status, blocker, alert or reconciliation code from the existing chain.",
            $"Investigate {exactCode} at its authoritative source component; do not infer a successful state.",
            AutomaticResolutionPossible: severity is not OperationalBreakSeverity.Critical,
            BlocksTrading: severity is OperationalBreakSeverity.Error or OperationalBreakSeverity.Critical,
            BlocksAccounting: category is "FILL" or "POSITION_LEDGER" or "RECONCILIATION",
            EvidenceRequirements: "Exact source fact, timestamp and content-addressed evidence when available.",
            Supersedes: null,
            IntroducedByContractVersion: OperationalReportingContract.Version);
}
