// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QQ.Production.Intraday.Infrastructure.PostgreSql;

#nullable disable

namespace QQ.Production.Intraday.Infrastructure.PostgreSql.Migrations
{
    [DbContext(typeof(PmsShadowDbContext))]
    [Migration("20260721175549_CorrectGitCommitIdentityContract")]
    partial class CorrectGitCommitIdentityContract
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pms_shadow")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowAccountSnapshotRow", b =>
                {
                    b.Property<Guid>("AccountSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("account_snapshot_id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("AsOfUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("as_of_utc");

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("authority");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("base_currency");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("classification");

                    b.Property<Guid>("IngestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingestion_id");

                    b.Property<decimal>("NavOrEquity")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("nav_or_equity");

                    b.Property<DateOnly>("ReportDate")
                        .HasColumnType("date")
                        .HasColumnName("report_date");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("scope");

                    b.Property<string>("SnapshotSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("snapshot_sha256");

                    b.Property<string>("SourceArtifactSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_artifact_sha256");

                    b.HasKey("AccountSnapshotId");

                    b.HasIndex("IngestionId", "SnapshotSha256")
                        .IsUnique();

                    b.HasIndex("ReportDate", "AsOfUtc");

                    b.ToTable("account_snapshots", "pms_shadow", t =>
                        {
                            t.HasCheckConstraint("ck_account_not_real", "account_id <> '921640160'");

                            t.HasCheckConstraint("ck_account_snapshot_sha256", "snapshot_sha256 ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_account_source_sha256", "source_artifact_sha256 ~ '^[0-9a-f]{64}$'");
                        });
                });

            modelBuilder.Entity("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowBrokerAdjustedDriftStageRow", b =>
                {
                    b.Property<Guid>("StageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("stage_id");

                    b.Property<string>("Blocker")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("blocker");

                    b.Property<bool>("Calculated")
                        .HasColumnType("boolean")
                        .HasColumnName("calculated");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("classification");

                    b.Property<bool>("EmptyStateInferred")
                        .HasColumnType("boolean")
                        .HasColumnName("empty_state_inferred");

                    b.Property<Guid>("ModelRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_run_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("status");

                    b.Property<Guid>("WorkingLeavesObservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("working_leaves_observation_id");

                    b.HasKey("StageId");

                    b.HasIndex("ModelRunId")
                        .IsUnique();

                    b.HasIndex("WorkingLeavesObservationId");

                    b.ToTable("broker_adjusted_drift_stages", "pms_shadow", t =>
                        {
                            t.HasCheckConstraint("ck_broker_adjusted_blocker", "blocker = 'BROKER_WORKING_LEAVES_UNOBSERVABLE'");

                            t.HasCheckConstraint("ck_broker_adjusted_not_calculated", "NOT calculated AND NOT empty_state_inferred");
                        });
                });

            modelBuilder.Entity("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowCycleResultRow", b =>
                {
                    b.Property<Guid>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("result_id");

                    b.Property<string>("BrokerSendStatus")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("broker_send_status");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("classification");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<bool>("ExecutionAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("execution_allowed");

                    b.Property<Guid>("IngestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingestion_id");

                    b.Property<string>("ManualPaperCycleStatus")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("manual_paper_cycle_status");

                    b.Property<Guid>("ModelRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_run_id");

                    b.Property<bool>("NoBrokerRoute")
                        .HasColumnType("boolean")
                        .HasColumnName("no_broker_route");

                    b.Property<bool>("NoFixMessage")
                        .HasColumnType("boolean")
                        .HasColumnName("no_fix_message");

                    b.Property<bool>("NotAnOrder")
                        .HasColumnType("boolean")
                        .HasColumnName("not_an_order");

                    b.Property<bool>("OrderEntryEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("order_entry_enabled");

                    b.Property<string>("R009Status")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("r009_status");

                    b.Property<int>("TradeIntentCount")
                        .HasColumnType("integer")
                        .HasColumnName("trade_intent_count");

                    b.HasKey("ResultId");

                    b.HasIndex("CompletedAtUtc");

                    b.HasIndex("ModelRunId");

                    b.HasIndex("IngestionId", "ModelRunId")
                        .IsUnique();

                    b.ToTable("cycle_results", "pms_shadow", t =>
                        {
                            t.HasCheckConstraint("ck_cycle_result_broker_send", "broker_send_status = 'DISABLED_NO_ORDER_ENTRY'");

                            t.HasCheckConstraint("ck_cycle_result_no_order", "NOT execution_allowed AND not_an_order AND no_broker_route AND no_fix_message AND NOT order_entry_enabled AND trade_intent_count = 0");
                        });
                });

            modelBuilder.Entity("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowIngestionRow", b =>
                {
                    b.Property<Guid>("IngestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ingestion_id");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("classification");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("ContractVersion")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("contract_version");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("environment");

                    b.Property<string>("RowsetSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("rowset_sha256");

                    b.Property<string>("SourceEvidenceSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_evidence_sha256");

                    b.Property<string>("SourceGate")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("source_gate");

                    b.Property<string>("SourceSessionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_session_id");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("IngestionId");

                    b.HasIndex("CompletedAtUtc");

                    b.HasIndex("SourceSessionId")
                        .IsUnique();

                    b.HasIndex("SourceSessionId", "SourceEvidenceSha256", "RowsetSha256")
                        .IsUnique();

                    b.ToTable("ingestions", "pms_shadow", t =>
                        {
                            t.HasCheckConstraint("ck_ingestions_classification", "classification = 'EVIDENCE_ONLY_NONACCOUNTING'");

                            t.HasCheckConstraint("ck_ingestions_environment", "environment = 'LMAX_TEST_EOD_ONLY'");

                            t.HasCheckConstraint("ck_ingestions_rowset_sha256", "rowset_sha256 ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_ingestions_source_evidence_sha256", "source_evidence_sha256 ~ '^[0-9a-f]{64}$'");
                        });
                });

            modelBuilder.Entity("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowMarketDataObservationRow", b =>
                {
                    b.Property<Guid>("MarketDataSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_data_snapshot_id");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<decimal>("Ask")
                        .HasPrecision(38, 28)
                        .HasColumnType("numeric(38,28)")
                        .HasColumnName("ask");

                    b.Property<decimal>("Bid")
                        .HasPrecision(38, 28)
                        .HasColumnType("numeric(38,28)")
                        .HasColumnName("bid");

                    b.Property<DateTimeOffset>("EventTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_time_utc");

                    b.Property<string>("LmaxInstrumentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("lmax_instrument_id");

                    b.Property<string>("ProjectionLegSecurityIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("projection_leg_security_ids_json");

                    b.Property<string>("ProjectionMethod")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("projection_method");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<string>("SecurityId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("security_id");

                    b.Property<string>("SourceCaptureId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("source_capture_id");

                    b.Property<string>("SourceFileSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_file_sha256");

                    b.Property<long>("StalenessMilliseconds")
                        .HasColumnType("bigint")
                        .HasColumnName("staleness_milliseconds");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("symbol");

                    b.HasKey("MarketDataSnapshotId", "InstrumentId");

                    b.ToTable("market_data_observations", "pms_shadow", t =>
                        {
                            t.HasCheckConstraint("ck_market_bid_ask", "bid > 0 AND ask >= bid");

                            t.HasCheckConstraint("ck_market_source_sha256", "source_file_sha256 ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_market_staleness", "staleness_milliseconds >= 0");
                        });
                });

            modelBuilder.Entity("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowMarketDataSnapshotRow", b =>
                {
                    b.Property<Guid>("MarketDataSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("market_data_snapshot_id");

                    b.Property<DateTimeOffset>("AsOfUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("as_of_utc");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("classification");

                    b.Property<Guid>("IngestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingestion_id");

                    b.Property<int>("ObservationCount")
                        .HasColumnType("integer")
                        .HasColumnName("observation_count");

                    b.Property<string>("SnapshotSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("snapshot_sha256");

                    b.HasKey("MarketDataSnapshotId");

                    b.HasIndex("AsOfUtc");

                    b.HasIndex("IngestionId", "SnapshotSha256")
                        .IsUnique();

                    b.ToTable("market_data_snapshots", "pms_shadow", t =>
                        {
                            t.HasCheckConstraint("ck_market_observation_count", "observation_count > 0");

                            t.HasCheckConstraint("ck_market_snapshot_sha256", "snapshot_sha256 ~ '^[0-9a-f]{64}$'");
                        });
                });

            modelBuilder.Entity("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowModelRunRow", b =>
                {
                    b.Property<Guid>("ModelRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("model_run_id");

                    b.Property<bool>("AccountingEligible")
                        .HasColumnType("boolean")
                        .HasColumnName("accounting_eligible");

                    b.Property<DateTimeOffset>("AsOfUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("as_of_utc");

                    b.Property<decimal>("BenchmarkParameter")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("benchmark_parameter");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("classification");

                    b.Property<string>("ContractVersion")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("contract_version");

                    b.Property<string>("CoreMasterCommitId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("core_master_commit_id");

                    b.Property<string>("CoreMasterObjectFormat")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("core_master_object_format")
                        .HasComputedColumnSql("CASE WHEN length(core_master_commit_id) = 40 THEN 'sha1' WHEN length(core_master_commit_id) = 64 THEN 'sha256' ELSE 'invalid' END", true);

                    b.Property<string>("EngineSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("engine_sha256");

                    b.Property<bool>("ExecutionAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("execution_allowed");

                    b.Property<string>("ExternalModelRunId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_model_run_id");

                    b.Property<Guid>("IngestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingestion_id");

                    b.Property<int>("NativeExitCode")
                        .HasColumnType("integer")
                        .HasColumnName("native_exit_code");

                    b.Property<bool>("NotAnOrder")
                        .HasColumnType("boolean")
                        .HasColumnName("not_an_order");

                    b.Property<Guid>("OutputArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("output_artifact_id");

                    b.Property<string>("OutputSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("output_sha256");

                    b.Property<string>("PackageSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("package_sha256");

                    b.Property<Guid>("QubesInputSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("qubes_input_snapshot_id");

                    b.Property<string>("R083Status")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("r083_status");

                    b.Property<string>("SemanticStatus")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("semantic_status");

                    b.Property<string>("SourceDomainModel")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("source_domain_model");

                    b.Property<string>("StrategyId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("strategy_id");

                    b.Property<DateTimeOffset>("TargetCloseUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("target_close_utc");

                    b.Property<int>("WrapperExitCode")
                        .HasColumnType("integer")
                        .HasColumnName("wrapper_exit_code");

                    b.HasKey("ModelRunId");

                    b.HasIndex("OutputArtifactId");

                    b.HasIndex("QubesInputSnapshotId");

                    b.HasIndex("TargetCloseUtc");

                    b.HasIndex("ExternalModelRunId", "OutputSha256")
                        .IsUnique();

                    b.HasIndex("IngestionId", "StrategyId")
                        .IsUnique();

                    b.ToTable("model_runs", "pms_shadow", t =>
                        {
                            t.HasCheckConstraint("ck_model_run_artifact_hashes", "package_sha256 ~ '^[0-9a-f]{64}$' AND engine_sha256 ~ '^[0-9a-f]{64}$' AND output_sha256 ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_model_run_core_master_commit_identity", "core_master_object_format IN ('sha1', 'sha256') AND ((core_master_object_format = 'sha1' AND core_master_commit_id ~ '^[0-9a-f]{40}$') OR (core_master_object_format = 'sha256' AND core_master_commit_id ~ '^[0-9a-f]{64}$'))");

                            t.HasCheckConstraint("ck_model_run_exit_codes", "wrapper_exit_code = 0 AND native_exit_code = 0");

                            t.HasCheckConstraint("ck_model_run_no_order", "NOT accounting_eligible AND NOT execution_allowed AND not_an_order");
                        });
                });

            modelBuilder.Entity("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowPositionOnlyDriftRow", b =>
                {
                    b.Property<Guid>("StageId")
                        .HasColumnType("uuid")
                        .HasColumnName("stage_id");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<DateTimeOffset>("AsOfUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("as_of_utc");

                    b.Property<decimal>("CurrentBaseQuantity")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("current_base_quantity");

                    b.Property<Guid>("ModelRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_run_id");

                    b.Property<decimal>("PositionOnlyDeltaBaseQuantity")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("position_only_delta_base_quantity");

                    b.Property<string>("SecurityId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("security_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("status");

                    b.Property<decimal>("TargetBaseQuantity")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("target_base_quantity");

                    b.HasKey("StageId", "InstrumentId");

                    b.HasIndex("ModelRunId", "InstrumentId")
                        .IsUnique();

                    b.ToTable("position_only_drifts", "pms_shadow");
                });

            modelBuilder.Entity("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowPositionOnlyDriftStageRow", b =>
                {
                    b.Property<Guid>("StageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("stage_id");

                    b.Property<DateTimeOffset>("AsOfUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("as_of_utc");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("classification");

                    b.Property<Guid>("ModelRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_run_id");

                    b.Property<Guid>("PositionSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_snapshot_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("status");

                    b.HasKey("StageId");

                    b.HasIndex("AsOfUtc");

                    b.HasIndex("ModelRunId")
                        .IsUnique();

                    b.HasIndex("PositionSnapshotId");

                    b.ToTable("position_only_drift_stages", "pms_shadow");
                });

            modelBuilder.Entity("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowPositionSnapshotLineRow", b =>
                {
                    b.Property<Guid>("PositionSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_snapshot_id");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<decimal>("CurrentBaseQuantity")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("current_base_quantity");

                    b.Property<string>("SecurityId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("security_id");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("symbol");

                    b.HasKey("PositionSnapshotId", "InstrumentId");

                    b.ToTable("position_snapshot_lines", "pms_shadow");
                });

            modelBuilder.Entity("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowPositionSnapshotRow", b =>
                {
                    b.Property<Guid>("PositionSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("position_snapshot_id");

                    b.Property<Guid>("AccountSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_snapshot_id");

                    b.Property<DateTimeOffset>("AsOfUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("as_of_utc");

                    b.Property<bool>("BrokerAuthority")
                        .HasColumnType("boolean")
                        .HasColumnName("broker_authority");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("classification");

                    b.Property<bool>("EmptyStateWasExplicitlyObserved")
                        .HasColumnType("boolean")
                        .HasColumnName("empty_state_was_explicitly_observed");

                    b.Property<bool>("EmptyStateWasInferred")
                        .HasColumnType("boolean")
                        .HasColumnName("empty_state_was_inferred");

                    b.Property<Guid>("IngestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingestion_id");

                    b.Property<DateOnly>("ReportDate")
                        .HasColumnType("date")
                        .HasColumnName("report_date");

                    b.Property<string>("SnapshotSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("snapshot_sha256");

                    b.HasKey("PositionSnapshotId");

                    b.HasIndex("AccountSnapshotId");

                    b.HasIndex("IngestionId", "SnapshotSha256")
                        .IsUnique();

                    b.HasIndex("ReportDate", "AsOfUtc");

                    b.ToTable("position_snapshots", "pms_shadow", t =>
                        {
                            t.HasCheckConstraint("ck_position_empty_not_inferred", "NOT empty_state_was_inferred");

                            t.HasCheckConstraint("ck_position_snapshot_sha256", "snapshot_sha256 ~ '^[0-9a-f]{64}$'");
                        });
                });

            modelBuilder.Entity("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowQubesInputSnapshotRow", b =>
                {
                    b.Property<Guid>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("snapshot_id");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("classification");

                    b.Property<int>("GapCount")
                        .HasColumnType("integer")
                        .HasColumnName("gap_count");

                    b.Property<string>("GapLedgerSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("gap_ledger_sha256");

                    b.Property<Guid>("IngestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingestion_id");

                    b.Property<Guid>("InputArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("input_artifact_id");

                    b.Property<string>("InputSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("input_sha256");

                    b.Property<string>("MappingSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("mapping_sha256");

                    b.Property<Guid>("OverlayArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("overlay_artifact_id");

                    b.Property<string>("OverlaySha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("overlay_sha256");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("provenance");

                    b.Property<int>("SourceInstrumentCount")
                        .HasColumnType("integer")
                        .HasColumnName("source_instrument_count");

                    b.Property<Guid>("SourceSnapshotArtifactId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_snapshot_artifact_id");

                    b.Property<string>("SourceSnapshotSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_snapshot_sha256");

                    b.Property<string>("StrategyId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("strategy_id");

                    b.Property<DateTimeOffset>("TargetCloseUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("target_close_utc");

                    b.HasKey("SnapshotId");

                    b.HasIndex("InputArtifactId");

                    b.HasIndex("InputSha256")
                        .IsUnique();

                    b.HasIndex("OverlayArtifactId");

                    b.HasIndex("SourceSnapshotArtifactId");

                    b.HasIndex("TargetCloseUtc");

                    b.HasIndex("IngestionId", "StrategyId")
                        .IsUnique();

                    b.ToTable("qubes_input_snapshots", "pms_shadow", t =>
                        {
                            t.HasCheckConstraint("ck_qubes_counts", "source_instrument_count > 0 AND gap_count >= 0");

                            t.HasCheckConstraint("ck_qubes_input_sha256", "input_sha256 ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_qubes_overlay_sha256", "overlay_sha256 ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_qubes_source_sha256", "source_snapshot_sha256 ~ '^[0-9a-f]{64}$'");
                        });
                });

            modelBuilder.Entity("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowSecurityMappingRow", b =>
                {
                    b.Property<Guid>("IngestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingestion_id");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<string>("LmaxInstrumentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("lmax_instrument_id");

                    b.Property<string>("MappingSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("mapping_sha256");

                    b.Property<decimal>("PriceIncrement")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("price_increment");

                    b.Property<decimal>("QuantityIncrement")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("quantity_increment");

                    b.Property<decimal>("QuantityMultiplier")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("quantity_multiplier");

                    b.Property<string>("SecurityId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("security_id");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("symbol");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_id");

                    b.Property<Guid>("VenueInstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("venue_instrument_id");

                    b.HasKey("IngestionId", "InstrumentId");

                    b.HasIndex("IngestionId", "LmaxInstrumentId")
                        .IsUnique();

                    b.HasIndex("IngestionId", "SecurityId")
                        .IsUnique();

                    b.ToTable("security_mappings", "pms_shadow", t =>
                        {
                            t.HasCheckConstraint("ck_security_mapping_positive", "quantity_multiplier > 0 AND quantity_increment > 0 AND price_increment > 0");

                            t.HasCheckConstraint("ck_security_mapping_sha256", "mapping_sha256 ~ '^[0-9a-f]{64}$'");
                        });
                });

            modelBuilder.Entity("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowSourceArtifactRow", b =>
                {
                    b.Property<Guid>("ArtifactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("artifact_id");

                    b.Property<string>("ArtifactType")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("artifact_type");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("classification");

                    b.Property<string>("ContractVersion")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("contract_version");

                    b.Property<Guid>("IngestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingestion_id");

                    b.Property<string>("LogicalUri")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("logical_uri");

                    b.Property<DateTimeOffset>("ProducedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("produced_at_utc");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("source_system");

                    b.HasKey("ArtifactId");

                    b.HasIndex("IngestionId", "Sha256")
                        .IsUnique();

                    b.HasIndex("Sha256", "ArtifactType", "SizeBytes", "LogicalUri")
                        .IsUnique();

                    b.ToTable("source_artifacts", "pms_shadow", t =>
                        {
                            t.HasCheckConstraint("ck_source_artifacts_sha256", "sha256 ~ '^[0-9a-f]{64}$'");
                        });
                });

            modelBuilder.Entity("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowTargetPositionRow", b =>
                {
                    b.Property<Guid>("StageId")
                        .HasColumnType("uuid")
                        .HasColumnName("stage_id");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("classification");

                    b.Property<Guid>("ModelRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_run_id");

                    b.Property<string>("RoundingPolicy")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("rounding_policy");

                    b.Property<string>("SecurityId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("security_id");

                    b.Property<string>("SizingPolicy")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("sizing_policy");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("status");

                    b.Property<decimal>("TargetBaseQuantity")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("target_base_quantity");

                    b.Property<decimal>("TargetNotionalUsd")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("target_notional_usd");

                    b.Property<decimal>("TargetVenueQuantity")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)")
                        .HasColumnName("target_venue_quantity");

                    b.HasKey("StageId", "InstrumentId");

                    b.HasIndex("ModelRunId", "InstrumentId")
                        .IsUnique();

                    b.ToTable("target_positions", "pms_shadow");
                });

            modelBuilder.Entity("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowTargetPositionStageRow", b =>
                {
                    b.Property<Guid>("StageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("stage_id");

                    b.Property<Guid>("AccountSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_snapshot_id");

                    b.Property<bool>("AccountingEligible")
                        .HasColumnType("boolean")
                        .HasColumnName("accounting_eligible");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("classification");

                    b.Property<bool>("ExecutionAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("execution_allowed");

                    b.Property<Guid>("MarketDataSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_data_snapshot_id");

                    b.Property<Guid>("ModelRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_run_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("status");

                    b.HasKey("StageId");

                    b.HasIndex("AccountSnapshotId");

                    b.HasIndex("MarketDataSnapshotId");

                    b.HasIndex("ModelRunId")
                        .IsUnique();

                    b.ToTable("target_position_stages", "pms_shadow", t =>
                        {
                            t.HasCheckConstraint("ck_target_position_stage_no_order", "NOT accounting_eligible AND NOT execution_allowed");
                        });
                });

            modelBuilder.Entity("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowTargetWeightRow", b =>
                {
                    b.Property<Guid>("ModelRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_run_id");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<string>("LineageVersion")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("lineage_version");

                    b.Property<string>("OutputSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("output_sha256");

                    b.Property<string>("SecurityId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("security_id");

                    b.Property<int>("SourceOrder")
                        .HasColumnType("integer")
                        .HasColumnName("source_order");

                    b.Property<string>("SourceRowKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source_row_key");

                    b.Property<DateTimeOffset>("TargetCloseUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("target_close_utc");

                    b.Property<decimal>("Weight")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)")
                        .HasColumnName("weight");

                    b.HasKey("ModelRunId", "InstrumentId");

                    b.HasIndex("TargetCloseUtc");

                    b.HasIndex("ModelRunId", "SourceOrder")
                        .IsUnique();

                    b.HasIndex("ModelRunId", "SourceRowKey")
                        .IsUnique();

                    b.ToTable("target_weights", "pms_shadow", t =>
                        {
                            t.HasCheckConstraint("ck_target_weight_output_sha256", "output_sha256 ~ '^[0-9a-f]{64}$'");
                        });
                });

            modelBuilder.Entity("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowWorkingLeavesObservationRow", b =>
                {
                    b.Property<Guid>("WorkingLeavesObservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("working_leaves_observation_id");

                    b.Property<DateTimeOffset>("AsOfUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("as_of_utc");

                    b.Property<bool>("BrokerAuthority")
                        .HasColumnType("boolean")
                        .HasColumnName("broker_authority");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("classification");

                    b.Property<bool>("EmptyStateInferred")
                        .HasColumnType("boolean")
                        .HasColumnName("empty_state_inferred");

                    b.Property<bool>("EmptyStateObserved")
                        .HasColumnType("boolean")
                        .HasColumnName("empty_state_observed");

                    b.Property<string>("Impact")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("impact");

                    b.Property<Guid>("IngestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingestion_id");

                    b.Property<bool>("ObservationAttempted")
                        .HasColumnType("boolean")
                        .HasColumnName("observation_attempted");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("reason");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("source_system");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)")
                        .HasColumnName("status");

                    b.HasKey("WorkingLeavesObservationId");

                    b.HasIndex("IngestionId")
                        .IsUnique();

                    b.ToTable("working_leaves_observations", "pms_shadow", t =>
                        {
                            t.HasCheckConstraint("ck_working_leaves_not_empty_not_inferred", "NOT empty_state_observed AND NOT empty_state_inferred AND NOT broker_authority");

                            t.HasCheckConstraint("ck_working_leaves_unavailable", "status = 'UNAVAILABLE_WITH_CURRENT_LMAX_INTERFACES'");
                        });
                });

            modelBuilder.Entity("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowAccountSnapshotRow", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowIngestionRow", null)
                        .WithMany()
                        .HasForeignKey("IngestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowBrokerAdjustedDriftStageRow", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowModelRunRow", null)
                        .WithMany()
                        .HasForeignKey("ModelRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowWorkingLeavesObservationRow", null)
                        .WithMany()
                        .HasForeignKey("WorkingLeavesObservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowCycleResultRow", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowIngestionRow", null)
                        .WithMany()
                        .HasForeignKey("IngestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowModelRunRow", null)
                        .WithMany()
                        .HasForeignKey("ModelRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowMarketDataObservationRow", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowMarketDataSnapshotRow", null)
                        .WithMany()
                        .HasForeignKey("MarketDataSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowMarketDataSnapshotRow", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowIngestionRow", null)
                        .WithMany()
                        .HasForeignKey("IngestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowModelRunRow", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowIngestionRow", null)
                        .WithMany()
                        .HasForeignKey("IngestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowSourceArtifactRow", null)
                        .WithMany()
                        .HasForeignKey("OutputArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowQubesInputSnapshotRow", null)
                        .WithMany()
                        .HasForeignKey("QubesInputSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowPositionOnlyDriftRow", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowPositionOnlyDriftStageRow", null)
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowTargetWeightRow", null)
                        .WithMany()
                        .HasForeignKey("ModelRunId", "InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowPositionOnlyDriftStageRow", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowModelRunRow", null)
                        .WithMany()
                        .HasForeignKey("ModelRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowPositionSnapshotRow", null)
                        .WithMany()
                        .HasForeignKey("PositionSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowPositionSnapshotLineRow", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowPositionSnapshotRow", null)
                        .WithMany()
                        .HasForeignKey("PositionSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowPositionSnapshotRow", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowAccountSnapshotRow", null)
                        .WithMany()
                        .HasForeignKey("AccountSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowIngestionRow", null)
                        .WithMany()
                        .HasForeignKey("IngestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowQubesInputSnapshotRow", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowIngestionRow", null)
                        .WithMany()
                        .HasForeignKey("IngestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowSourceArtifactRow", null)
                        .WithMany()
                        .HasForeignKey("InputArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowSourceArtifactRow", null)
                        .WithMany()
                        .HasForeignKey("OverlayArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowSourceArtifactRow", null)
                        .WithMany()
                        .HasForeignKey("SourceSnapshotArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowSecurityMappingRow", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowIngestionRow", null)
                        .WithMany()
                        .HasForeignKey("IngestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowSourceArtifactRow", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowIngestionRow", null)
                        .WithMany()
                        .HasForeignKey("IngestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowTargetPositionRow", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowTargetPositionStageRow", null)
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowTargetWeightRow", null)
                        .WithMany()
                        .HasForeignKey("ModelRunId", "InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowTargetPositionStageRow", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowAccountSnapshotRow", null)
                        .WithMany()
                        .HasForeignKey("AccountSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowMarketDataSnapshotRow", null)
                        .WithMany()
                        .HasForeignKey("MarketDataSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowModelRunRow", null)
                        .WithMany()
                        .HasForeignKey("ModelRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowTargetWeightRow", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowModelRunRow", null)
                        .WithMany()
                        .HasForeignKey("ModelRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowWorkingLeavesObservationRow", b =>
                {
                    b.HasOne("QQ.Production.Intraday.Infrastructure.PostgreSql.PmsShadowIngestionRow", null)
                        .WithMany()
                        .HasForeignKey("IngestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
