param(
    [string]$InstrumentCsvFile = "",
    [string]$SecondaryCsvFile = "",
    [switch]$ReviewRecords
)

$ErrorActionPreference = "Stop"
$repoRoot = Split-Path -Parent $PSScriptRoot
$results = @()
$expected = [ordered]@{
    GBPUSD = "4002"
    EURGBP = "4003"
    USDJPY = "4004"
    AUDUSD = "4007"
}

function Add-Result([string]$Category, [string]$Check, [string]$Status, [string]$Detail) {
    $script:results += [ordered]@{ category = $Category; check = $Check; status = $Status; detail = $Detail }
    Write-Host ("{0}: {1} / {2} - {3}" -f $Status, $Category, $Check, $Detail)
}

function Resolve-LocalPath([string]$Path) {
    if ([string]::IsNullOrWhiteSpace($Path)) { return $Path }
    if ([IO.Path]::IsPathRooted($Path)) { return $Path }
    return Join-Path $repoRoot $Path
}

function Normalize-Symbol([string]$Value) {
    if ([string]::IsNullOrWhiteSpace($Value)) { return "" }
    return $Value.Replace("/", "").Replace(" ", "").ToUpperInvariant()
}

function Get-TextHit([string[]]$Path, [string[]]$Pattern) {
    $existing = @($Path | Where-Object { Test-Path -LiteralPath $_ })
    if ($existing.Count -eq 0) { return @() }
    return @(Select-String -Path $existing -Pattern $Pattern -SimpleMatch -ErrorAction SilentlyContinue)
}

function Get-ColumnValue($Row, [string]$ColumnName) {
    $property = @($Row.PSObject.Properties | Where-Object { $_.Name.Trim() -eq $ColumnName } | Select-Object -First 1)
    if ($property.Count -eq 0) { return "" }
    return [string]$property[0].Value
}

function Read-InstrumentCsv([string]$Path) {
    if (-not (Test-Path -LiteralPath $Path)) {
        Add-Result "CSV" "CSV file exists" "FAIL" "Missing: $Path"
        return @()
    }
    $text = Get-Content -Raw -LiteralPath $Path
    if ($text -match '(?i)(password|secret|token|apikey|api_key|privatekey|private_key|authorization|bearer|\b553=|\b554=|host=|user=|account)') {
        Add-Result "CSV" "CSV has no sensitive content" "FAIL" "Credential-shaped content found in $Path"
        return @()
    }
    Add-Result "CSV" "CSV has no sensitive content" "PASS" "No credential-shaped content in $Path"
    return @(Import-Csv -LiteralPath $Path | ForEach-Object {
        [ordered]@{
            source = Split-Path -Leaf $Path
            instrumentName = Get-ColumnValue $_ "Instrument Name"
            lmaxId = Get-ColumnValue $_ "LMAX ID"
            lmaxSymbol = Get-ColumnValue $_ "LMAX symbol"
        }
    })
}

Write-Host "LMAX Read-Only Runtime Phase 6M CSV SecurityID Records Gate"
Write-Host "Local-only gate. No LMAX connection, no SecurityListRequest, no snapshots, no replay, no credentials, no orders, and no mutation."

$modelFile = Join-Path $repoRoot "src/QQ.Production.Intraday.Infrastructure.Lmax/LmaxReadOnlyInstrumentCsvSecurityIdSource.cs"
$scriptFile = Join-Path $PSScriptRoot "new-lmax-readonly-securityid-records-from-instrument-csv.ps1"
$reviewScript = Join-Path $PSScriptRoot "review-lmax-readonly-securityid-confirmation-records.ps1"
$testFile = Join-Path $repoRoot "tests/QQ.Production.Intraday.Tests.Unit/LmaxReadOnlyInstrumentCsvSecurityIdExtractorTests.cs"

foreach ($item in @(
    @{ Name = "CSV extractor model"; Path = $modelFile },
    @{ Name = "CSV record generation script"; Path = $scriptFile },
    @{ Name = "Confirmation record review script"; Path = $reviewScript },
    @{ Name = "CSV extractor tests"; Path = $testFile }
)) {
    if (Test-Path -LiteralPath $item.Path) { Add-Result "Files" "$($item.Name) exists" "PASS" $item.Path }
    else { Add-Result "Files" "$($item.Name) exists" "FAIL" "Missing: $($item.Path)" }
}

$modelText = if (Test-Path -LiteralPath $modelFile) { Get-Content -Raw -LiteralPath $modelFile } else { "" }
foreach ($marker in @("LmaxReadOnlyInstrumentCsvSecurityIdExtractor", "ExpectedDemoLondonSecurityId", "ObservedTokyoSecurityIds", "IsApprovedForExternalRun: false")) {
    if ($modelText.Contains($marker)) { Add-Result "Model" "Marker $marker" "PASS" "CSV extractor marker found." }
    else { Add-Result "Model" "Marker $marker" "FAIL" "CSV extractor marker missing." }
}

$extraction = $null
if ([string]::IsNullOrWhiteSpace($InstrumentCsvFile)) {
    Add-Result "CSV" "Instrument CSV supplied" "WARN" "No CSV supplied; extractor/generator are ready but records cannot be generated by this gate."
} else {
    $rows = @()
    $rows += Read-InstrumentCsv (Resolve-LocalPath $InstrumentCsvFile)
    if (-not [string]::IsNullOrWhiteSpace($SecondaryCsvFile)) {
        $rows += Read-InstrumentCsv (Resolve-LocalPath $SecondaryCsvFile)
    }

    $selected = [ordered]@{}
    $tokyo = [ordered]@{}
    foreach ($symbol in $expected.Keys) {
        $matches = @($rows | Where-Object {
            (Normalize-Symbol $_.instrumentName) -eq $symbol -or (Normalize-Symbol $_.lmaxSymbol) -eq $symbol
        })
        $selectedIds = @($matches | Where-Object { $_.lmaxId.StartsWith("400", [StringComparison]::Ordinal) } | ForEach-Object { $_.lmaxId } | Sort-Object -Unique)
        $tokyo[$symbol] = @($matches | Where-Object { $_.lmaxId.StartsWith("600", [StringComparison]::Ordinal) } | ForEach-Object { $_.lmaxId } | Sort-Object -Unique)
        if ($selectedIds.Count -eq 1 -and $selectedIds[0] -eq $expected[$symbol]) {
            Add-Result "CSV" "$symbol selected DemoLondon SecurityID" "PASS" "$symbol=$($selectedIds[0])"
            $selected[$symbol] = $selectedIds[0]
        } elseif ($selectedIds.Count -eq 0) {
            Add-Result "CSV" "$symbol selected DemoLondon SecurityID" "FAIL" "No 400x value found."
        } else {
            Add-Result "CSV" "$symbol selected DemoLondon SecurityID" "FAIL" "Expected $($expected[$symbol]); found $($selectedIds -join ', ')."
        }
    }
    $extraction = [ordered]@{
        selectedValues = $selected
        tokyoIdsObservedButNotSelected = $tokyo
    }
}

$review = $null
if ($ReviewRecords.IsPresent) {
    $reviewOutput = & $reviewScript
    foreach ($line in $reviewOutput) { Write-Host $line }
    $reviewReportPath = Join-Path $repoRoot "artifacts/readiness/phase6h-securityid-confirmation-records-review.json"
    if (Test-Path -LiteralPath $reviewReportPath) {
        $review = Get-Content -Raw -LiteralPath $reviewReportPath | ConvertFrom-Json
        if ([string]$review.finalDecision -eq "PASS") {
            Add-Result "Records" "Confirmation record review PASS" "PASS" "AcceptedForPlanning=$($review.acceptedForPlanningCount); Missing=$($review.missingInstrumentCount); Conflicts=$($review.conflictCount)."
        } else {
            Add-Result "Records" "Confirmation record review PASS" "WARN" "Review decision=$($review.finalDecision); AcceptedForPlanning=$($review.acceptedForPlanningCount); Missing=$($review.missingInstrumentCount); Conflicts=$($review.conflictCount); Invalid=$($review.invalidRecordCount)."
        }
        if ([bool]$review.isApprovedForExternalRun) {
            Add-Result "Records" "Records remain non-executable" "FAIL" "Review report marked IsApprovedForExternalRun=true."
        } else {
            Add-Result "Records" "Records remain non-executable" "PASS" "Review report keeps IsApprovedForExternalRun=false."
        }
    } else {
        Add-Result "Records" "Review report written" "FAIL" "Missing: $reviewReportPath"
    }
} else {
    Add-Result "Records" "Review records requested" "WARN" "Use -ReviewRecords after generating CSV-backed confirmation records."
}

$apiProgram = Join-Path $repoRoot "src/QQ.Production.Intraday.Api/Program.cs"
$workerProgram = Join-Path $repoRoot "src/QQ.Production.Intraday.Worker/Program.cs"
$apiWorker = @($apiProgram, $workerProgram)
$registrationHits = Get-TextHit $apiWorker @("RealLmaxGateway", "ExternalReadOnlyPrototypeGateway", "LmaxVenueGatewaySkeleton", "SecurityListRequest")
if ($registrationHits.Count -eq 0 -and (Select-String -Path $apiProgram -Pattern "FakeLmaxGateway" -SimpleMatch -Quiet)) {
    Add-Result "Registration" "API/Worker remain FakeLmaxGateway only" "PASS" "No SecurityList or real gateway registration found."
} else {
    Add-Result "Registration" "API/Worker remain FakeLmaxGateway only" "FAIL" (($registrationHits | ForEach-Object { "$($_.Path):$($_.LineNumber)" }) -join "; ")
}

foreach ($scan in @(
    @{ Category = "Scheduler"; Check = "No scheduler/polling added"; Patterns = @("PeriodicTimer", "System.Threading.Timer", "SecurityListPoll") },
    @{ Category = "Replay"; Check = "Runtime does not submit to shadow replay"; Patterns = @("SubmitToShadowReplay = true", "SubmittedToShadowReplay = true", "ReplaySubmitAsync") },
    @{ Category = "Orders"; Check = "No order surface"; Patterns = @("NewOrderSingle", "OrderCancelRequest", "OrderCancelReplaceRequest", "SubmitOrder") },
    @{ Category = "Mutation"; Check = "No trading-state mutation references"; Patterns = @("PersistTrade", "TradingState") }
)) {
    $hits = Get-TextHit $apiWorker $scan.Patterns
    if ($hits.Count -eq 0) { Add-Result $scan.Category $scan.Check "PASS" "No marker found in API/Worker startup." }
    else { Add-Result $scan.Category $scan.Check "FAIL" (($hits | ForEach-Object { "$($_.Path):$($_.LineNumber)" }) -join "; ") }
}

Add-Result "Runtime" "External LMAX connection" "PASS" "This gate does not connect to LMAX."
Add-Result "Discovery" "SecurityListRequest" "PASS" "This gate does not run SecurityListRequest."
Add-Result "Snapshot" "MarketData snapshot" "PASS" "This gate does not request snapshots."
Add-Result "Replay" "Manual replay" "PASS" "This gate does not replay evidence."
Add-Result "Credentials" "Credential values" "PASS" "This gate does not require or print credential values."

$failed = @($results | Where-Object { $_.status -eq "FAIL" })
$warnings = @($results | Where-Object { $_.status -eq "WARN" })
$decision = if ($failed.Count -gt 0) { "FAIL" } elseif ($warnings.Count -gt 0) { "PASS_WITH_KNOWN_WARNINGS" } else { "PASS" }

$reportDir = Join-Path $repoRoot "artifacts/readiness"
New-Item -ItemType Directory -Path $reportDir -Force | Out-Null
$reportPath = Join-Path $reportDir "phase6m-csv-securityid-records-gate.json"
[ordered]@{
    generatedAtUtc = [DateTimeOffset]::UtcNow.ToString("o")
    finalDecision = $decision
    phase = "6M"
    scope = "Create AcceptedForPlanning SecurityID Records from Uploaded LMAX Instrument CSVs, Still IsApprovedForExternalRun=false"
    extraction = $extraction
    recordReview = $review
    isApprovedForExternalRun = $false
    externalConnectionAttempted = $false
    securityListRequestAttempted = $false
    marketDataSnapshotAttempted = $false
    replayAttempted = $false
    runtimeShadowReplaySubmit = $false
    schedulerOrPollingAdded = $false
    orderSubmissionAdded = $false
    gatewayRegistrationAdded = $false
    tradingMutationAdded = $false
    results = $results
} | ConvertTo-Json -Depth 10 | Set-Content -LiteralPath $reportPath -Encoding UTF8

Write-Host ""
Write-Host "FinalDecision: $decision"
Write-Host "Report: $reportPath"
if ($decision -eq "FAIL") { exit 1 }
