param([string]$ExecutionPlanFile="")
$ErrorActionPreference="Stop";$repoRoot=Split-Path -Parent $PSScriptRoot;$results=@()
function Add($c,$k,$s,$d){$script:results+=[ordered]@{category=$c;check=$k;status=$s;detail=$d};Write-Host ("{0}: {1} / {2} - {3}" -f $s,$c,$k,$d)}
function Resolve-LocalPath([string]$p){if([string]::IsNullOrWhiteSpace($p)){return $p};if([IO.Path]::IsPathRooted($p)){$p}else{Join-Path $repoRoot $p}}
function Hits($paths,$patterns){$e=@($paths|?{Test-Path $_});if(!$e){return @()};@(Select-String -Path $e -Pattern $patterns -SimpleMatch -ErrorAction SilentlyContinue)}
Write-Host "LMAX Read-Only Runtime Phase 6T GBPUSD Execution Plan Gate"
Write-Host "Local-only gate. No LMAX connection, no snapshots, no replay, no credentials, no orders, and no mutation."
foreach($i in @(@{n="Execution plan model";p="src/QQ.Production.Intraday.Infrastructure.Lmax/LmaxReadOnlyGbpusdManualSnapshotExecutionPlan.cs"},@{n="Execution plan script";p="scripts/new-lmax-readonly-gbpusd-manual-snapshot-execution-plan.ps1"},@{n="Execution plan doc";p="docs/LMAX_READONLY_GBPUSD_MANUAL_SNAPSHOT_EXECUTION_PLAN.md"},@{n="Execution plan tests";p="tests/QQ.Production.Intraday.Tests.Unit/LmaxReadOnlyGbpusdManualSnapshotExecutionPlanTests.cs"})){ $p=Join-Path $repoRoot $i.p;if(Test-Path $p){Add "Files" "$($i.n) exists" "PASS" $p}else{Add "Files" "$($i.n) exists" "FAIL" "Missing $p"}}
if([string]::IsNullOrWhiteSpace($ExecutionPlanFile)){Add "ExecutionPlan" "Execution plan supplied" "WARN" "No execution plan supplied."}else{$p=Resolve-LocalPath $ExecutionPlanFile;if(Test-Path $p){$t=Get-Content -Raw $p;$e=$t|ConvertFrom-Json;if($t -match '(?i)(password|secret|token|apikey|api_key|privatekey|private_key|bearer|\b553=|\b554=|host=|user=|account)'){Add "ExecutionPlan" "No sensitive content" "FAIL" "Sensitive-shaped content found."}else{Add "ExecutionPlan" "No sensitive content" "PASS" "No credential-shaped content."};if([string]$e.decision -eq "PASS" -and [string]$e.symbol -eq "GBPUSD" -and [string]$e.planningSecurityId -eq "4002" -and -not[bool]$e.externalRunAuthorized -and -not[bool]$e.canRunExternalSnapshot -and -not[bool]$e.eligibleForManualSnapshotAttempt -and -not[bool]$e.isApprovedForExternalRun -and -not[bool]$e.schedulerOrPolling -and -not[bool]$e.runtimeShadowReplaySubmit -and -not[bool]$e.orderSubmission -and -not[bool]$e.tradingMutation){Add "ExecutionPlan" "GBPUSD plan non-executable" "PASS" "PASS with all execution flags false."}else{Add "ExecutionPlan" "GBPUSD plan non-executable" "FAIL" "Unsafe execution plan flags."};if([string]$e.futureCommandTemplate -match "DO NOT RUN IN PHASE 6T"){Add "ExecutionPlan" "Future command template marked non-executable" "PASS" "Template is explicitly not runnable in Phase 6T."}else{Add "ExecutionPlan" "Future command template marked non-executable" "FAIL" "Missing DO NOT RUN IN PHASE 6T."}}else{Add "ExecutionPlan" "Plan exists" "FAIL" "Missing $p"}}
$api=Join-Path $repoRoot "src/QQ.Production.Intraday.Api/Program.cs";$worker=Join-Path $repoRoot "src/QQ.Production.Intraday.Worker/Program.cs";$aw=@($api,$worker)
$reg=Hits $aw @("RealLmaxGateway","ExternalReadOnlyPrototypeGateway","LmaxVenueGatewaySkeleton","SecurityListRequest")
if($reg.Count-eq 0 -and (Select-String -Path $api -Pattern "FakeLmaxGateway" -SimpleMatch -Quiet)){Add "Registration" "API/Worker remain FakeLmaxGateway only" "PASS" "No real gateway registration found."}else{Add "Registration" "API/Worker remain FakeLmaxGateway only" "FAIL" (($reg|%{"$($_.Path):$($_.LineNumber)"})-join"; ")}
foreach($scan in @(@{c="Scheduler";k="No scheduler/polling added";p=@("PeriodicTimer","System.Threading.Timer","SecurityListPoll")},@{c="Replay";k="Runtime does not submit to shadow replay";p=@("SubmitToShadowReplay = true","SubmittedToShadowReplay = true","ReplaySubmitAsync")},@{c="Orders";k="No order surface";p=@("NewOrderSingle","OrderCancelRequest","OrderCancelReplaceRequest","SubmitOrder")},@{c="Mutation";k="No trading-state mutation references";p=@("PersistTrade","TradingState")})){ $h=Hits $aw $scan.p;if($h.Count-eq 0){Add $scan.c $scan.k "PASS" "No marker found in API/Worker startup."}else{Add $scan.c $scan.k "FAIL" (($h|%{"$($_.Path):$($_.LineNumber)"})-join"; ")}}
Add "Runtime" "External LMAX connection" "PASS" "This gate does not connect to LMAX.";Add "Snapshot" "MarketData snapshot" "PASS" "This gate does not request snapshots.";Add "Replay" "Manual replay" "PASS" "This gate does not replay evidence.";Add "Credentials" "Credential values" "PASS" "This gate does not require or print credential values."
$failed=@($results|? status -eq "FAIL");$warn=@($results|? status -eq "WARN");$decision=if($failed){"FAIL"}elseif($warn){"PASS_WITH_KNOWN_WARNINGS"}else{"PASS"}
$dir=Join-Path $repoRoot "artifacts/readiness";New-Item -ItemType Directory -Path $dir -Force|Out-Null;$path=Join-Path $dir "phase6t-gbpusd-execution-plan-gate.json"
[ordered]@{generatedAtUtc=[DateTimeOffset]::UtcNow.ToString("o");finalDecision=$decision;phase="6T";externalRunAuthorized=$false;isApprovedForExternalRun=$false;eligibleForManualSnapshotAttempt=$false;canRunExternalSnapshot=$false;schedulerStarted=$false;orderSubmissionAttempted=$false;shadowReplaySubmitAttempted=$false;tradingMutationAttempted=$false;results=$results}|ConvertTo-Json -Depth 10|Set-Content -LiteralPath $path -Encoding UTF8
Write-Host "";Write-Host "FinalDecision: $decision";Write-Host "Report: $path";if($decision-eq"FAIL"){exit 1}
