param(
    [string]$RepoRoot = (Split-Path -Parent $PSScriptRoot),
    [string]$OutputSubdir = "real-qubes-core-handoff-to-intraday-consumption-r001"
)

$ErrorActionPreference = "Stop"

$BuildScript = Join-Path $PSScriptRoot "build-real-qubes-core-handoff-to-intraday-consumption-r001.ps1"
& $BuildScript -RepoRoot $RepoRoot -OutputSubdir $OutputSubdir

$Dir = Join-Path $RepoRoot "artifacts\readiness\$OutputSubdir"

function Read-JsonFile([string]$Path) {
    if (-not (Test-Path -LiteralPath $Path)) { throw "Missing artifact: $Path" }
    Get-Content -Raw -LiteralPath $Path | ConvertFrom-Json
}

function Assert-True([bool]$Condition, [string]$Message) {
    if (-not $Condition) { throw $Message }
}

function Assert-Equal($Expected, $Actual, [string]$Message) {
    if ($Expected -ne $Actual) { throw "$Message Expected=[$Expected] Actual=[$Actual]" }
}

foreach ($name in @(
    "qubes-core-discovery-report-r001.json",
    "core-to-intraday-handoff-manifest-r001.json",
    "intraday-handoff-consumption-r001.json",
    "real-qubes-drift-and-orders-preview-r001.json",
    "real-qubes-lmax-order-manifest-preview-r001.json",
    "real-qubes-to-existing-lmax-run-scope-bridge-r001.json",
    "real-qubes-core-handoff-to-intraday-consumption-r001.json",
    "e2e-flow-coverage-after-real-qubes-handoff-r001.json",
    "real-qubes-core-handoff-to-intraday-consumption-summary-r001.md"
)) {
    Assert-True (Test-Path -LiteralPath (Join-Path $Dir $name)) "Required artifact missing: $name"
}

$main = Read-JsonFile (Join-Path $Dir "real-qubes-core-handoff-to-intraday-consumption-r001.json")
$manifest = Read-JsonFile (Join-Path $Dir "core-to-intraday-handoff-manifest-r001.json")
$consumer = Read-JsonFile (Join-Path $Dir "intraday-handoff-consumption-r001.json")
$orders = Read-JsonFile (Join-Path $Dir "real-qubes-lmax-order-manifest-preview-r001.json")
$bridge = Read-JsonFile (Join-Path $Dir "real-qubes-to-existing-lmax-run-scope-bridge-r001.json")
$coverage = Read-JsonFile (Join-Path $Dir "e2e-flow-coverage-after-real-qubes-handoff-r001.json")

Assert-True ($main.status -in @(
    "REAL_QUBES_CORE_HANDOFF_CONSUMED_R001",
    "REAL_QUBES_CORE_HANDOFF_CONSUMED_AND_ORDER_PREVIEW_READY_R001",
    "REAL_QUBES_CORE_HANDOFF_CONSUMED_AND_MATCHES_EXISTING_LMAX_RUN_R001",
    "BLOCKED_REAL_QUBES_CORE_OUTPUT_MISSING_R001",
    "BLOCKED_REAL_QUBES_CORE_OUTPUT_INVALID_R001",
    "BLOCKED_INTRADAY_HANDOFF_CONSUMPTION_FAILED_R001",
    "BLOCKED_MARKET_DATA_OR_INSTRUMENT_METADATA_MISSING_R001",
    "FIXTURE_ONLY_QUBES_HANDOFF_CONSUMED_R001",
    "AMBIGUOUS_QUBES_CORE_HANDOFF_EVIDENCE_R001"
)) "Unexpected main status."

foreach ($guard in @("trading_activity", "lmax_fix_api_call", "broker_api_call", "polygon_massive_call", "market_data_fetch", "broker_fetch", "account_data_fetch", "production_live_write", "production_live_ready", "trading_readiness_ready")) {
    Assert-Equal $false $main.global_guards.$guard "Guard $guard must remain false."
}

foreach ($order in @($orders.orders)) {
    if (-not [string]::IsNullOrWhiteSpace([string]$order.security_id)) {
        Assert-Equal "8" $order.security_id_source_tag22 "Tag 22 must equal 8 when tag 48/security_id is present."
    }
    Assert-Equal $false $order.production_live "Order preview must not be production/live."
}

if ($main.real_qubes_core_output_accepted -eq $true) {
    Assert-Equal $true $manifest.generated_by_qubes_core "Accepted real manifest must be generated by Qubes/Core."
    Assert-Equal $false $manifest.synthetic_fixture "Accepted real manifest must not be synthetic."
    Assert-Equal $true $consumer.manifest_loaded "Accepted real manifest must be consumed."
}

if ($bridge.existing_lmax_run_attributed_to_real_qubes_core -eq $true) {
    Assert-Equal $true $main.real_qubes_core_output_accepted "Existing LMAX attribution requires accepted real Qubes/Core output."
    Assert-Equal $true $bridge.hashes_match "Existing LMAX attribution requires matching hashes/signatures."
    Assert-Equal $true $bridge.run_ids_match "Existing LMAX attribution requires matching run IDs."
}

Assert-Equal "BLOCKED" $coverage.flow_coverage.production_live_trading_readiness "Production/live/trading coverage must remain blocked."

Write-Host "REAL_QUBES_CORE_HANDOFF_TO_INTRADAY_CONSUMPTION_R001_GATE_PASS"
