param([string]$AttemptGateFile="")
$ErrorActionPreference="Stop";$repoRoot=Split-Path -Parent $PSScriptRoot;$results=@()
function Add($c,$k,$s,$d){$script:results+=[ordered]@{category=$c;check=$k;status=$s;detail=$d};Write-Host ("{0}: {1} / {2} - {3}" -f $s,$c,$k,$d)}
function Resolve-LocalPath([string]$p){if([string]::IsNullOrWhiteSpace($p)){return $p};if([IO.Path]::IsPathRooted($p)){$p}else{Join-Path $repoRoot $p}}
function Hits($paths,$patterns){$e=@($paths|?{Test-Path $_});if(!$e){return @()};@(Select-String -Path $e -Pattern $patterns -SimpleMatch -ErrorAction SilentlyContinue)}
Write-Host "LMAX Read-Only Runtime Phase 6S Single-Instrument Attempt Gate"
Write-Host "Local-only gate. No LMAX connection, no snapshots, no replay, no credentials, no orders, and no mutation."
foreach($i in @(@{n="Attempt gate model";p="src/QQ.Production.Intraday.Infrastructure.Lmax/LmaxReadOnlySingleInstrumentSnapshotAttemptGate.cs"},@{n="Attempt gate creation script";p="scripts/new-lmax-readonly-single-instrument-snapshot-attempt-gate.ps1"},@{n="Attempt gate review script";p="scripts/review-lmax-readonly-single-instrument-snapshot-attempt-gates.ps1"},@{n="Attempt gate tests";p="tests/QQ.Production.Intraday.Tests.Unit/LmaxReadOnlySingleInstrumentSnapshotAttemptGateTests.cs"})){ $p=Join-Path $repoRoot $i.p;if(Test-Path $p){Add "Files" "$($i.n) exists" "PASS" $p}else{Add "Files" "$($i.n) exists" "FAIL" "Missing $p"}}
if([string]::IsNullOrWhiteSpace($AttemptGateFile)){Add "AttemptGate" "Attempt gate supplied" "WARN" "No attempt gate supplied."}else{$p=Resolve-LocalPath $AttemptGateFile;if(Test-Path $p){$t=Get-Content -Raw $p;$g=$t|ConvertFrom-Json;if($t -match '(?i)(password|secret|token|apikey|api_key|privatekey|private_key|authorization|bearer|\b553=|\b554=|host=|user=|account)'){Add "AttemptGate" "No sensitive content" "FAIL" "Sensitive-shaped content found."}else{Add "AttemptGate" "No sensitive content" "PASS" "No credential-shaped content."};if([string]$g.gateDecision -eq "PASS" -and -not[bool]$g.canRunExternalSnapshot -and -not[bool]$g.isApprovedForExternalRun -and -not[bool]$g.eligibleForManualSnapshotAttempt -and -not[bool]$g.externalConnectionAttempted -and -not[bool]$g.snapshotAttempted -and -not[bool]$g.replayAttempted -and -not[bool]$g.orderSubmissionAttempted -and -not[bool]$g.shadowReplaySubmitAttempted -and -not[bool]$g.tradingMutationAttempted -and -not[bool]$g.schedulerStarted){Add "AttemptGate" "$($g.symbol) gate non-executable" "PASS" "PASS with all execution flags false."}else{Add "AttemptGate" "$($g.symbol) gate non-executable" "FAIL" "Unsafe attempt gate flags."}}else{Add "AttemptGate" "Gate exists" "FAIL" "Missing $p"}}
$api=Join-Path $repoRoot "src/QQ.Production.Intraday.Api/Program.cs";$worker=Join-Path $repoRoot "src/QQ.Production.Intraday.Worker/Program.cs";$aw=@($api,$worker)
$reg=Hits $aw @("RealLmaxGateway","ExternalReadOnlyPrototypeGateway","LmaxVenueGatewaySkeleton","SecurityListRequest")
if($reg.Count-eq 0 -and (Select-String -Path $api -Pattern "FakeLmaxGateway" -SimpleMatch -Quiet)){Add "Registration" "API/Worker remain FakeLmaxGateway only" "PASS" "No real gateway registration found."}else{Add "Registration" "API/Worker remain FakeLmaxGateway only" "FAIL" (($reg|%{"$($_.Path):$($_.LineNumber)"})-join"; ")}
foreach($scan in @(@{c="Scheduler";k="No scheduler/polling added";p=@("PeriodicTimer","System.Threading.Timer","SecurityListPoll")},@{c="Replay";k="Runtime does not submit to shadow replay";p=@("SubmitToShadowReplay = true","SubmittedToShadowReplay = true","ReplaySubmitAsync")},@{c="Orders";k="No order surface";p=@("NewOrderSingle","OrderCancelRequest","OrderCancelReplaceRequest","SubmitOrder")},@{c="Mutation";k="No trading-state mutation references";p=@("PersistTrade","TradingState")})){ $h=Hits $aw $scan.p;if($h.Count-eq 0){Add $scan.c $scan.k "PASS" "No marker found in API/Worker startup."}else{Add $scan.c $scan.k "FAIL" (($h|%{"$($_.Path):$($_.LineNumber)"})-join"; ")}}
Add "Runtime" "External LMAX connection" "PASS" "This gate does not connect to LMAX.";Add "Snapshot" "MarketData snapshot" "PASS" "This gate does not request snapshots.";Add "Replay" "Manual replay" "PASS" "This gate does not replay evidence.";Add "Credentials" "Credential values" "PASS" "This gate does not require or print credential values."
$failed=@($results|? status -eq "FAIL");$warn=@($results|? status -eq "WARN");$decision=if($failed){"FAIL"}elseif($warn){"PASS_WITH_KNOWN_WARNINGS"}else{"PASS"}
$dir=Join-Path $repoRoot "artifacts/readiness";New-Item -ItemType Directory -Path $dir -Force|Out-Null;$path=Join-Path $dir "phase6s-single-instrument-attempt-gate.json"
[ordered]@{generatedAtUtc=[DateTimeOffset]::UtcNow.ToString("o");finalDecision=$decision;phase="6S";isApprovedForExternalRun=$false;eligibleForManualSnapshotAttempt=$false;canRunExternalSnapshot=$false;externalConnectionAttempted=$false;snapshotAttempted=$false;replayAttempted=$false;schedulerStarted=$false;orderSubmissionAttempted=$false;shadowReplaySubmitAttempted=$false;tradingMutationAttempted=$false;results=$results}|ConvertTo-Json -Depth 10|Set-Content -LiteralPath $path -Encoding UTF8
Write-Host "";Write-Host "FinalDecision: $decision";Write-Host "Report: $path";if($decision-eq"FAIL"){exit 1}
