param([string]$ExecutionPlanFile="", [string]$Phase6TGateReportFile="", [string]$SignoffFile="")
$ErrorActionPreference="Stop";$repoRoot=Split-Path -Parent $PSScriptRoot;$results=@()
function Add($c,$k,$s,$d){$script:results+=[ordered]@{category=$c;check=$k;status=$s;detail=$d};Write-Host ("{0}: {1} / {2} - {3}" -f $s,$c,$k,$d)}
function Resolve-LocalPath([string]$p){if([string]::IsNullOrWhiteSpace($p)){return $p};if([IO.Path]::IsPathRooted($p)){$p}else{Join-Path $repoRoot $p}}
function Hits($paths,$patterns){$e=@($paths|?{Test-Path $_});if(!$e){return @()};@(Select-String -Path $e -Pattern $patterns -SimpleMatch -ErrorAction SilentlyContinue)}
Write-Host "LMAX Read-Only Runtime Phase 6U GBPUSD Operator Signoff Gate"
Write-Host "Local-only gate. No LMAX connection, no snapshots, no replay, no credentials, no orders, and no mutation."
foreach($i in @(@{n="Operator signoff model";p="src/QQ.Production.Intraday.Infrastructure.Lmax/LmaxReadOnlyGbpusdManualSnapshotOperatorSignoff.cs"},@{n="Operator signoff script";p="scripts/new-lmax-readonly-gbpusd-manual-snapshot-operator-signoff.ps1"},@{n="Operator signoff review script";p="scripts/review-lmax-readonly-gbpusd-manual-snapshot-operator-signoffs.ps1"},@{n="Operator signoff tests";p="tests/QQ.Production.Intraday.Tests.Unit/LmaxReadOnlyGbpusdManualSnapshotOperatorSignoffTests.cs"})){ $p=Join-Path $repoRoot $i.p;if(Test-Path $p){Add "Files" "$($i.n) exists" "PASS" $p}else{Add "Files" "$($i.n) exists" "FAIL" "Missing $p"}}
if($ExecutionPlanFile){$p=Resolve-LocalPath $ExecutionPlanFile;if(Test-Path $p){$e=Get-Content -Raw $p|ConvertFrom-Json;if([string]$e.decision -eq "PASS"){Add "ExecutionPlan" "Source execution plan PASS" "PASS" $p}else{Add "ExecutionPlan" "Source execution plan PASS" "FAIL" "Expected PASS"}}else{Add "ExecutionPlan" "Source execution plan exists" "FAIL" "Missing $p"}}
if($Phase6TGateReportFile){$p=Resolve-LocalPath $Phase6TGateReportFile;if(Test-Path $p){$g=Get-Content -Raw $p|ConvertFrom-Json;if([string]$g.finalDecision -eq "PASS"){Add "Phase6TGate" "Source Phase 6T gate PASS" "PASS" $p}else{Add "Phase6TGate" "Source Phase 6T gate PASS" "FAIL" "Expected PASS"}}else{Add "Phase6TGate" "Source Phase 6T gate exists" "FAIL" "Missing $p"}}
if([string]::IsNullOrWhiteSpace($SignoffFile)){Add "Signoff" "Operator signoff supplied" "WARN" "No signoff supplied."}else{$p=Resolve-LocalPath $SignoffFile;if(Test-Path $p){$t=Get-Content -Raw $p;$s=$t|ConvertFrom-Json;if($t -match '(?i)(password|secret|token|apikey|api_key|privatekey|private_key|authorization|bearer|\b553=|\b554=|host=|user=|account)'){Add "Signoff" "No sensitive content" "FAIL" "Sensitive-shaped content found."}else{Add "Signoff" "No sensitive content" "PASS" "No credential-shaped content."};if([string]$s.signoffDecision -eq "SignedForPlanning" -and -not[bool]$s.canRunExternalSnapshot -and -not[bool]$s.isApprovedForExternalRun -and -not[bool]$s.eligibleForManualSnapshotAttempt -and -not[bool]$s.externalConnectionAttempted -and -not[bool]$s.snapshotAttempted -and -not[bool]$s.replayAttempted -and -not[bool]$s.orderSubmissionAttempted -and -not[bool]$s.shadowReplaySubmitAttempted -and -not[bool]$s.tradingMutationAttempted -and -not[bool]$s.schedulerStarted){Add "Signoff" "$($s.symbol) signoff non-executable" "PASS" "SignedForPlanning with all execution flags false."}else{Add "Signoff" "$($s.symbol) signoff non-executable" "FAIL" "Unsafe signoff flags."}}else{Add "Signoff" "Signoff exists" "FAIL" "Missing $p"}}
$api=Join-Path $repoRoot "src/QQ.Production.Intraday.Api/Program.cs";$worker=Join-Path $repoRoot "src/QQ.Production.Intraday.Worker/Program.cs";$aw=@($api,$worker)
$reg=Hits $aw @("RealLmaxGateway","ExternalReadOnlyPrototypeGateway","LmaxVenueGatewaySkeleton","SecurityListRequest")
if($reg.Count-eq 0 -and (Select-String -Path $api -Pattern "FakeLmaxGateway" -SimpleMatch -Quiet)){Add "Registration" "API/Worker remain FakeLmaxGateway only" "PASS" "No real gateway registration found."}else{Add "Registration" "API/Worker remain FakeLmaxGateway only" "FAIL" (($reg|%{"$($_.Path):$($_.LineNumber)"})-join"; ")}
foreach($scan in @(@{c="Scheduler";k="No scheduler/polling added";p=@("PeriodicTimer","System.Threading.Timer","SecurityListPoll")},@{c="Replay";k="Runtime does not submit to shadow replay";p=@("SubmitToShadowReplay = true","SubmittedToShadowReplay = true","ReplaySubmitAsync")},@{c="Orders";k="No order surface";p=@("NewOrderSingle","OrderCancelRequest","OrderCancelReplaceRequest","SubmitOrder")},@{c="Mutation";k="No trading-state mutation references";p=@("PersistTrade","TradingState")})){ $h=Hits $aw $scan.p;if($h.Count-eq 0){Add $scan.c $scan.k "PASS" "No marker found in API/Worker startup."}else{Add $scan.c $scan.k "FAIL" (($h|%{"$($_.Path):$($_.LineNumber)"})-join"; ")}}
Add "Runtime" "External LMAX connection" "PASS" "This gate does not connect to LMAX.";Add "Snapshot" "MarketData snapshot" "PASS" "This gate does not request snapshots.";Add "Replay" "Manual replay" "PASS" "This gate does not replay evidence.";Add "Credentials" "Credential values" "PASS" "This gate does not require or print credential values."
$failed=@($results|? status -eq "FAIL");$warn=@($results|? status -eq "WARN");$decision=if($failed){"FAIL"}elseif($warn){"PASS_WITH_KNOWN_WARNINGS"}else{"PASS"}
$dir=Join-Path $repoRoot "artifacts/readiness";New-Item -ItemType Directory -Path $dir -Force|Out-Null;$path=Join-Path $dir "phase6u-gbpusd-operator-signoff-gate.json"
[ordered]@{generatedAtUtc=[DateTimeOffset]::UtcNow.ToString("o");finalDecision=$decision;phase="6U";isApprovedForExternalRun=$false;eligibleForManualSnapshotAttempt=$false;canRunExternalSnapshot=$false;externalConnectionAttempted=$false;snapshotAttempted=$false;replayAttempted=$false;schedulerStarted=$false;orderSubmissionAttempted=$false;shadowReplaySubmitAttempted=$false;tradingMutationAttempted=$false;results=$results}|ConvertTo-Json -Depth 10|Set-Content -LiteralPath $path -Encoding UTF8
Write-Host "";Write-Host "FinalDecision: $decision";Write-Host "Report: $path";if($decision-eq"FAIL"){exit 1}
